#!/usr/bin/env bash
# Comprehensive HTML Generation Tests
# Tests: Integration, Responsive Design, HTML Validity, Visual Regression

set -e  # Exit on error

REQVIRE_CMD="${REQVIRE_BIN:-}"
if [ -z "$REQVIRE_CMD" ]; then
  echo "REQVIRE_BIN is not set"
  exit 1
fi

TEST_MODEL_DIR="$(mktemp -d /tmp/reqvire-html-model-XXXXXX)"
OUTPUT_DIR="/tmp/reqvire-test-output"

mkdir -p "$TEST_MODEL_DIR/requirements/System"
git -C "$TEST_MODEL_DIR" init > /dev/null 2>&1
cat > "$TEST_MODEL_DIR/requirements/Requirements.md" << 'EOF'
# Elements

### Root Requirement

#### Metadata
  * type: capability
---

### Root System Requirement

#### Metadata
  * type: requirement

#### Relations
  * specify: [Root Requirement](#root-requirement)
---
EOF

cat > "$TEST_MODEL_DIR/requirements/System/Core.md" << 'EOF'
# Elements

### Core Requirement

#### Metadata
  * type: requirement

#### Relations
  * derivedFrom: [Root System Requirement](../Requirements.md#root-system-requirement)
---
EOF

echo "=== HTML Generation Tests ==="
echo

# ========================================
# 1. INTEGRATION TESTS
# ========================================
echo "1. Running Integration Tests..."

# Generate all pages
cd "$TEST_MODEL_DIR" && "$REQVIRE_CMD" export --output "$OUTPUT_DIR"

# Verify primary and supporting pages exist
echo "  - Checking core pages exist..."
test -f "$OUTPUT_DIR/index.html"
test -f "$OUTPUT_DIR/model.html"
test -f "$OUTPUT_DIR/knowledgegraph.html"
test -f "$OUTPUT_DIR/kn2.html"
test -f "$OUTPUT_DIR/traces.html"
test -f "$OUTPUT_DIR/traceflow.html"
test -f "$OUTPUT_DIR/coverage.html"
test -f "$OUTPUT_DIR/resources.html"

# Test each page contains navigation
echo "  - Checking navigation present..."
grep -q "reqvire-nav" "$OUTPUT_DIR/index.html"
grep -q "Containment" "$OUTPUT_DIR/index.html"
grep -q "Model" "$OUTPUT_DIR/index.html"
grep -q "Knowledge Graph" "$OUTPUT_DIR/index.html"
grep -q "Traces" "$OUTPUT_DIR/index.html"
grep -q "Ontologies" "$OUTPUT_DIR/index.html"
if grep -q 'traceflow.html.*TraceFlow' "$OUTPUT_DIR/index.html"; then
  echo "TraceFlow must not be exposed in the primary Explorer header"
  exit 1
fi
if grep -q 'coverage.html.*Coverage' "$OUTPUT_DIR/index.html"; then
  echo "Coverage must not be exposed in the primary Explorer header"
  exit 1
fi
if grep -q 'resources.html.*Resources' "$OUTPUT_DIR/index.html"; then
  echo "Resources must not be exposed in the primary Explorer header"
  exit 1
fi
if grep -q "Generated by" "$OUTPUT_DIR/index.html"; then
  echo "Generated footer must not waste Explorer page space"
  exit 1
fi
grep -q "reqvire-help-button" "$OUTPUT_DIR/index.html"
grep -q "knowledgegraph.html.*Knowledge Graph" "$OUTPUT_DIR/index.html"
ONTO_NAV_POS=$(grep -b -o 'ontologies.html.*Ontologies' "$OUTPUT_DIR/index.html" | head -1 | cut -d: -f1)
KG_NAV_POS=$(grep -b -o 'knowledgegraph.html.*Knowledge Graph' "$OUTPUT_DIR/index.html" | head -1 | cut -d: -f1)
if [ -z "$ONTO_NAV_POS" ] || [ -z "$KG_NAV_POS" ] || [ "$KG_NAV_POS" -le "$ONTO_NAV_POS" ]; then
  echo "Knowledge Graph must be the far-right primary Explorer link after Ontologies"
  exit 1
fi

# Test relative links from nested file
echo "  - Testing relative links..."
cat > "$TEST_MODEL_DIR/requirements/System/Test.md" << 'EOF'
# Elements

### Test Requirement

This is a test requirement for validating nested file exports.

#### Metadata
  * type: requirement

#### Relations
  * derivedFrom: [Core Requirement](Core.md#core-requirement)
EOF
cd "$TEST_MODEL_DIR" && "$REQVIRE_CMD" export --output "$OUTPUT_DIR" 2>&1 | grep -q "Total Markdown files exported"
grep -q 'href="../../index.html"' "$OUTPUT_DIR/requirements/System/Test.html"

# Test visualizations present
echo "  - Checking visualizations..."
grep -q "mermaid" "$OUTPUT_DIR/model.html"
grep -q "d3" "$OUTPUT_DIR/index.html"
grep -q "knowledgeGraphData" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "kn2GraphData" "$OUTPUT_DIR/kn2.html"
grep -q 'id="kn2-cross-subgraph-overlay"' "$OUTPUT_DIR/kn2.html"
grep -q 'id="kn2-verification-overlay"' "$OUTPUT_DIR/kn2.html"
grep -q 'id="kn2-trace-overlay"' "$OUTPUT_DIR/kn2.html"
grep -q "Cross-subgraph overlays" "$OUTPUT_DIR/kn2.html"
grep -q "kn2-overlay-count" "$OUTPUT_DIR/kn2.html"
grep -q "cy.nodes('\\[node_type = \"concept\"\\]').hide()" "$OUTPUT_DIR/kn2.html"
grep -q "sigma@3.0.0" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "graphology@0.25.4" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "graphology-layout-forceatlas2@0.10.1" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "Project knowledge graph explorer" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "Root Requirement" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "Root System Requirement" "$OUTPUT_DIR/knowledgegraph.html"
grep -q '"label":"specifiedBy"' "$OUTPUT_DIR/knowledgegraph.html"
if grep -q '"label":"specify"' "$OUTPUT_DIR/knowledgegraph.html"; then
  echo "Knowledge Graph must render canonical Mermaid relation directions, not opposite relation duplicates"
  exit 1
fi
grep -q "Fact Inspector" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "knowledge-graph-sidebar" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "knowledge-graph-container" "$OUTPUT_DIR/knowledgegraph.html"
grep -q 'data-filter-value="resource" aria-pressed="false"' "$OUTPUT_DIR/knowledgegraph.html"
if grep -q 'data-filter-value="concept"\|kg-dot-concept' "$OUTPUT_DIR/knowledgegraph.html"; then
  echo "Knowledge Graph must not expose concept references as a separate node category; they are resource/relationship evidence"
  exit 1
fi
grep -q "height: calc(100vh - 50px)" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "ensureCanvasSize" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "assignInitialPositions" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "ForceAtlas2" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "\\[Reqvire KG\\]" "$OUTPUT_DIR/knowledgegraph.html"
grep -q ".kg-dot-requirement { background: #673AB7" "$OUTPUT_DIR/knowledgegraph.html"
grep -q ".kg-dot-verification { background: #4CAF50" "$OUTPUT_DIR/knowledgegraph.html"
grep -q -- "--reqvire-surface-hover: #e8e4da" "$OUTPUT_DIR/knowledgegraph.html"
grep -q -- "--reqvire-surface-active: #ddd6c7" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "kg-results button:hover" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "var(--reqvire-surface-hover, #e8e4da)" "$OUTPUT_DIR/knowledgegraph.html"
grep -q "var(--reqvire-surface-active, #ddd6c7)" "$OUTPUT_DIR/knowledgegraph.html"
grep -q ".ontology-dot-resource { background: #e8e4da" "$OUTPUT_DIR/ontologies.html"
if grep -Eq '#cfd8d6|#dbe7ef|#edf0ed|#edf0e9|#dbeafe|#eef2ff|#f5f3ff|#f0f9ff|#eff6ff|#e2e8f0|rgba\(232, 238, 234' "$OUTPUT_DIR/knowledgegraph.html" "$OUTPUT_DIR/ontologies.html"; then
  echo "Explorer pages must not use stale gray-green or blue-tinted selection/evidence backgrounds"
  exit 1
fi
KG_FILE="$OUTPUT_DIR/knowledgegraph.html" node - <<'NODE'
const fs = require('fs');
const html = fs.readFileSync(process.env.KG_FILE, 'utf8');
const match = html.match(/const knowledgeGraphData = (.*?);<\/script>/s);
if (!match) {
  console.error('knowledgeGraphData script not found');
  process.exit(1);
}
const data = JSON.parse(match[1]);
const ids = new Set(data.nodes.map(node => node.id));
const missing = data.edges.filter(edge => !ids.has(edge.source) || !ids.has(edge.target));
if (data.nodes.length < 2 || data.edges.length < 1 || missing.length > 0) {
  console.error(`Invalid Knowledge Graph data: nodes=${data.nodes.length}, edges=${data.edges.length}, missingEndpoints=${missing.length}`);
  process.exit(1);
}
const typedNodes = data.nodes.filter(node => node.type).length;
if (typedNodes !== data.nodes.length) {
  console.error(`Knowledge Graph nodes must carry exported type values: typed=${typedNodes}, total=${data.nodes.length}`);
  process.exit(1);
}
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match => match[1]);
const renderer = scripts.find(script => script.includes('assignInitialPositions') && script.includes('forceAtlas2'));
if (!renderer) {
  console.error('Knowledge Graph renderer script not found');
  process.exit(1);
}
if (!renderer.includes('d.node_type') || !renderer.includes('d.type')) {
  console.error('Knowledge Graph renderer must normalize exported node type values before filtering');
  process.exit(1);
}
if (!renderer.includes('new Graph') || !renderer.includes('new Sigma') || !renderer.includes('adjustSizes: true')) {
  console.error('Knowledge Graph renderer must use Graphology, Sigma, and size-aware ForceAtlas2 layout');
  process.exit(1);
}
if (!renderer.includes("import { Sigma }")) {
  console.error('Knowledge Graph renderer must import the Sigma constructor as a named ESM export');
  process.exit(1);
}
if (!renderer.includes("type: 'circle'") || !renderer.includes("type: 'arrow'") || !renderer.includes('reqvireType')) {
  console.error('Knowledge Graph renderer must keep Reqvire type metadata separate from Sigma renderer program types');
  process.exit(1);
}
if (!renderer.includes('activeFocusIds') || !renderer.includes("renderer.on('enterNode'") || !renderer.includes("renderer.on('leaveNode'") || !renderer.includes('dimNodeColor(attributes.color') || !renderer.includes('0.2')) {
  console.error('Knowledge Graph renderer must fade unconnected nodes during node hover or selection');
  process.exit(1);
}
if (!renderer.includes('activeFocusIds') || !renderer.includes('if (selectedId) ids.push(selectedId)') || !renderer.includes('if (hoveredId && hoveredId !== selectedId) ids.push(hoveredId)') || !renderer.includes('suppressNextStageClear') || !renderer.includes("renderer.on('clickStage'")) {
  console.error('Knowledge Graph renderer must keep clicked nodes pinned through pointer rollout and clear only on empty-stage click');
  process.exit(1);
}
if (!renderer.includes('isInAnyFocusNeighborhood') || !renderer.includes('isIncidentToAnyFocus')) {
  console.error('Knowledge Graph hover focus must be additive with clicked focus for neighborhood exploration');
  process.exit(1);
}
if (!renderer.includes('if (focusIds.length === 0 || attributes.hidden)') || !renderer.includes('result.hidden = true') || !renderer.includes('result.forceLabel = true')) {
  console.error('Knowledge Graph renderer must hide relation edges until a node is hovered or selected, then show only direct focused edges');
  process.exit(1);
}
if (!renderer.includes('fullLabel: node.label') || !renderer.includes('result.label = attributes.fullLabel || attributes.label ||')) {
  console.error('Knowledge Graph focused nodes must show full labels on hover or selection while normal labels remain density-truncated');
  process.exit(1);
}
if (!renderer.includes('kindPillHtml') || !renderer.includes('readableTextColor') || !renderer.includes('background:${background}')) {
  console.error('Knowledge Graph inspector kind badge must use the graph role color');
  process.exit(1);
}
if (!renderer.includes('kg-result-swatch') || !renderer.includes('button.appendChild(swatch)') || renderer.includes('${d.label} (${d.element_type})')) {
  console.error('Knowledge Graph search results must use role-color swatches and omit repeated type suffixes');
  process.exit(1);
}
if (!renderer.includes('centerOnNode') || !renderer.includes('getNodeDisplayData') || !renderer.includes('camera.animate')) {
  console.error('Knowledge Graph search and click selection must center the selected node in the graph viewport');
  process.exit(1);
}
if (!renderer.includes('graphNodeFill') || !renderer.includes("capability: '#1976D2'") || !renderer.includes("requirement: '#673AB7'") || !renderer.includes("verification: '#4CAF50'") || !renderer.includes("ontology: '#B08A00'")) {
  console.error('Knowledge Graph graph nodes, search swatches, and inspector badges must use the same saturated role colors');
  process.exit(1);
}
if (renderer.includes("'concept'") || renderer.includes('concept: [') || renderer.includes("concept: '#8D6E63'")) {
  console.error('Knowledge Graph must not retain a separate concept-reference node category; concept references use resource targets and relationship evidence');
  process.exit(1);
}
if (!renderer.includes('nodeBorder') || !renderer.includes("capability: '#0f4d8a'") || !renderer.includes("requirement: '#452480'") || !renderer.includes('border-color:${nodeBorder(d)}')) {
  console.error('Knowledge Graph role badges must use darker role borders as subtle accents');
  process.exit(1);
}
if (!renderer.includes('focusIds.includes(node)') || renderer.includes('highlighted')) {
  console.error('Knowledge Graph selection must not use Sigma highlight/glow rendering; unrelated nodes fade by alpha instead');
  process.exit(1);
}
if (renderer.includes('labelRenderer: renderKnowledgeLabel') || renderer.includes('hoverRenderer: () => {}') || renderer.includes('function renderKnowledgeLabel') || renderer.includes('roundedRect(context')) {
  console.error('Knowledge Graph node labels and rollover state must use Sigma 3 default rendering, not a custom label/hover renderer');
  process.exit(1);
}
if (!renderer.includes('parseHexColor') || !renderer.includes("parseHexColor('#d8d8d4')") || !renderer.includes('rgbToHex')) {
  console.error('Knowledge Graph dimmed nodes must use deterministic canvas-background blending instead of WebGL-sensitive alpha color strings');
  process.exit(1);
}
if (!renderer.includes('fieldHtml') || !renderer.includes('kg-fact-value')) {
  console.error('Knowledge Graph inspector facts must use stacked field rows for long identifiers and paths');
  process.exit(1);
}
try {
  new Function(renderer.replace(/^import .*$/gm, ''));
} catch (error) {
  console.error(`Knowledge Graph renderer script has invalid JavaScript syntax: ${error.message}`);
  process.exit(1);
}
NODE
KN2_FILE="$OUTPUT_DIR/kn2.html" node - <<'NODE'
const fs = require('fs');
const html = fs.readFileSync(process.env.KN2_FILE, 'utf8');
const match = html.match(/const kn2GraphData = (.*?);<\/script>/s);
if (!match) {
  console.error('kn2GraphData script not found');
  process.exit(1);
}
const data = JSON.parse(match[1]);
if (!Array.isArray(data.submodels) || data.submodels.length < 1) {
  console.error('KN2 graph data must include Reqvire root submodels for subgraph clustering');
  process.exit(1);
}
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(match => match[1]);
const renderer = scripts.find(script => script.includes('detectReqvireRootSubmodels') && script.includes('cytoscape('));
if (!renderer) {
  console.error('KN2 Cytoscape renderer script not found');
  process.exit(1);
}
if (!renderer.includes('const activeRelations = new Set([\'derive\', \'specify\', \'refine\'])')) {
  console.error('KN2 structural subgraph layout must default to Reqvire ownership hierarchy relations only');
  process.exit(1);
}
if (!renderer.includes('const submodelRoots = new Map') || !renderer.includes('detectReqvireRootSubmodels') || !renderer.includes('data.submodels.forEach')) {
  console.error('KN2 clustering must be seeded from exported Reqvire root submodels');
  process.exit(1);
}
if (!renderer.includes('return isSubmodelStructureCategory(category) && activeRelations.has(category)')) {
  console.error('KN2 layout/cluster edges must ignore overlays even when overlay edges are visible');
  process.exit(1);
}
if (!renderer.includes('verificationOverlay') || !renderer.includes('traceOverlay') || !renderer.includes("category === 'verify' || category === 'satisfy'") || !renderer.includes("category === 'trace'")) {
  console.error('KN2 must expose verification/satisfaction and trace as overlays, not structural relations');
  process.exit(1);
}
try {
  new Function(renderer);
} catch (error) {
  console.error(`KN2 renderer script has invalid JavaScript syntax: ${error.message}`);
  process.exit(1);
}
NODE
grep -q "Timed out waiting for one or more Mermaid diagrams" "$OUTPUT_DIR/model.html"
grep -q "desiredHeight = Math.min(Math.max(420, bbox.height + padding), viewportHeight)" "$OUTPUT_DIR/model.html"
MODEL_MERMAID_IMPORTS=$(grep -o "mermaid.esm.min.mjs" "$OUTPUT_DIR/model.html" | wc -l)
TRACES_MERMAID_IMPORTS=$(grep -o "mermaid.esm.min.mjs" "$OUTPUT_DIR/traces.html" | wc -l)
if [ "$MODEL_MERMAID_IMPORTS" -ne 1 ] || [ "$TRACES_MERMAID_IMPORTS" -ne 1 ]; then
  echo "Mermaid initializer should be included exactly once per Model/Traces page"
  echo "model imports: $MODEL_MERMAID_IMPORTS, traces imports: $TRACES_MERMAID_IMPORTS"
  exit 1
fi

echo "  ✅ Integration tests passed"
echo

# ========================================
# 2. RESPONSIVE DESIGN TESTS
# ========================================
echo "2. Running Responsive Design Tests..."

# Verify Tailwind CSS included
echo "  - Checking Tailwind CSS..."
grep -q "tailwindcss" "$OUTPUT_DIR/index.html"

# Verify compact Explorer header present
echo "  - Checking compact Explorer header..."
grep -q "reqvire-view-switcher" "$OUTPUT_DIR/index.html"
grep -q "openReqvireExplorerHelp" "$OUTPUT_DIR/index.html"

# Verify viewport meta tag
echo "  - Checking viewport meta tag..."
grep -q 'name="viewport"' "$OUTPUT_DIR/index.html"

# Verify removed mobile menu chrome stays removed
echo "  - Checking removed mobile menu chrome..."
if grep -q "mobile-menu-btn" "$OUTPUT_DIR/index.html"; then
  echo "Mobile hamburger menu should not be generated for the compact Explorer header"
  exit 1
fi

echo "  ✅ Responsive design tests passed"
echo

# ========================================
# 3. HTML VALIDITY TESTS
# ========================================
echo "3. Running HTML Validity Tests..."

# Basic HTML structure validation
for file in "$OUTPUT_DIR"/*.html; do
    filename=$(basename "$file")
    echo "  - Validating $filename..."

    # Check DOCTYPE
    head -1 "$file" | grep -q "<!DOCTYPE html>"

    # Check has <html>, <head>, <body>
    grep -q "<html lang=" "$file"
    grep -q "<head>" "$file"
    grep -q "<body" "$file"

    # Check all tags closed (simple check)
    OPEN=$(grep -o "<[^/][^>]*>" "$file" | grep -v "<!DOCTYPE" | grep -v "<meta" | grep -v "<link" | grep -v "<img" | wc -l)
    CLOSE=$(grep -o "</[^>]*>" "$file" | wc -l)

    echo "    Open tags: $OPEN, Close tags: $CLOSE"
done

echo "  ✅ HTML validity tests passed"
echo

# ========================================
# 4. VISUAL REGRESSION TESTS (Optional)
# ========================================
echo "4. Visual Regression Tests (skipped - requires Playwright)..."
echo "  - To enable: Install Playwright and uncomment section below"

# Uncomment to enable visual regression testing
# echo "  - Starting server..."
# cargo run -- serve --port 8888 &
# SERVER_PID=$!
# sleep 2
#
# echo "  - Taking screenshots at different viewports..."
# npx playwright screenshot --viewport-size=375,667 http://localhost:8888/index.html /tmp/mobile.png
# npx playwright screenshot --viewport-size=768,1024 http://localhost:8888/index.html /tmp/tablet.png
# npx playwright screenshot --viewport-size=1920,1080 http://localhost:8888/index.html /tmp/desktop.png
#
# echo "  - Comparing with baselines..."
# # Compare screenshots (requires image comparison tool)
# # diff /tmp/mobile.png tests/baselines/mobile.png
# # diff /tmp/tablet.png tests/baselines/tablet.png
# # diff /tmp/desktop.png tests/baselines/desktop.png
#
# kill $SERVER_PID
# echo "  ✅ Visual regression tests passed"

echo "  ⏭️  Visual regression tests skipped"
echo

# ========================================
# CLEANUP
# ========================================
rm -rf "$OUTPUT_DIR"
rm -rf "$TEST_MODEL_DIR"

echo "=== All HTML Generation Tests Passed ✅ ==="
