use crate::element::Element;
use crate::element::ElementType;
use crate::element::RequirementType;
use crate::error::ReqvireError;
use crate::filesystem;
use crate::git_commands;
use crate::graph_registry::GraphRegistry;
use crate::info_println;
use crate::relation;
use crate::utils;
use log::debug;
use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::path::Path;
use std::path::PathBuf;

/// Marker comment used to identify auto-generated diagrams
const AUTOGEN_DIAGRAM_MARKER: &str = "REQVIRE-AUTOGENERATED-DIAGRAM";

/// Default diagram direction (LR = left-to-right, TD = top-down)
pub const DEFAULT_DIAGRAM_DIRECTION: &str = "TD";

/// Model diagram report containing the complete hierarchical structure
#[derive(Debug, Serialize)]
pub struct ModelDiagramReport {
    pub folders: Vec<FolderNode>,
    pub relations: Vec<ModelRelation>,
}

/// Folder node in the model hierarchy
#[derive(Debug, Serialize)]
pub struct FolderNode {
    pub name: String,
    pub path: String,
    pub files: Vec<FileNode>,
}

/// File node in the model hierarchy
#[derive(Debug, Serialize)]
pub struct FileNode {
    pub name: String,
    pub path: String,
    pub elements: Vec<ElementNode>,
}

/// Element node in the model diagram
#[derive(Debug, Serialize)]
pub struct ElementNode {
    pub identifier: String,
    pub name: String,
    pub element_type: String,
    pub attachments: Vec<String>,
}

/// Relation between elements in the model
#[derive(Debug, Serialize)]
pub struct ModelRelation {
    pub source_id: String,
    pub target_id: String,
    pub target_label: String,
    pub relation_type: String,
    pub relation_label: String,
    pub arrow: String,
    pub is_external: bool,
}

/// Model diagram generator that follows the data-first pattern
pub struct ModelDiagramGenerator<'a> {
    registry: &'a GraphRegistry,
    root_element_id: Option<String>,
    forward_only: bool,
}

impl<'a> ModelDiagramGenerator<'a> {
    pub fn new(registry: &'a GraphRegistry, root_element_id: Option<&str>) -> Self {
        Self {
            registry,
            root_element_id: root_element_id.map(|s| s.to_string()),
            forward_only: false, // Default to bidirectional for backward compatibility
        }
    }

    pub fn new_with_mode(
        registry: &'a GraphRegistry,
        root_element_id: Option<&str>,
        forward_only: bool,
    ) -> Self {
        Self {
            registry,
            root_element_id: root_element_id.map(|s| s.to_string()),
            forward_only,
        }
    }

    /// Generate model diagram report
    pub fn generate(&self) -> Result<ModelDiagramReport, ReqvireError> {
        // Filter elements if root_element_id is provided
        let filtered_elements = if let Some(ref root_id) = self.root_element_id {
            if self.forward_only {
                collect_forward_related_elements(self.registry, root_id)
            } else {
                collect_related_elements(self.registry, root_id)
            }
        } else {
            // Include all elements
            self.registry
                .get_all_elements()
                .iter()
                .map(|e| e.identifier.clone())
                .collect()
        };

        // Group elements by file path, including only filtered elements
        let elements_by_file = group_elements_by_file_filtered(self.registry, &filtered_elements);

        // Group files by folder
        let files_by_folder = group_files_by_folder(&elements_by_file);

        // Build folder hierarchy
        let mut folders = Vec::new();
        let mut folder_names: Vec<&String> = files_by_folder.keys().collect();
        folder_names.sort();

        for folder_name in folder_names {
            let files = &files_by_folder[folder_name];
            let folder_path = if folder_name.is_empty() {
                "root".to_string()
            } else {
                folder_name.clone()
            };

            // Build file nodes
            let mut file_nodes = Vec::new();
            let mut sorted_files = files.clone();
            sorted_files.sort();

            for file_path_str in &sorted_files {
                if let Some(elements) = elements_by_file.get(file_path_str.as_str()) {
                    let file_name = Path::new(file_path_str.as_str())
                        .file_name()
                        .and_then(|n| n.to_str())
                        .unwrap_or(file_path_str.as_str())
                        .to_string();

                    let mut element_nodes = Vec::new();
                    // Sort elements by identifier for deterministic output
                    let mut sorted_elements = elements.clone();
                    sorted_elements.sort_by(|a, b| a.identifier.cmp(&b.identifier));
                    for element in sorted_elements {
                        let attachments: Vec<String> = element
                            .attachments
                            .iter()
                            .map(|a| match &a.target {
                                crate::element::AttachmentTarget::FilePath(path) => path
                                    .file_name()
                                    .map(|n| n.to_string_lossy().into_owned())
                                    .unwrap_or_else(|| path.to_string_lossy().into_owned()),
                                crate::element::AttachmentTarget::ElementIdentifier(id) => self
                                    .registry
                                    .get_element(id)
                                    .map(|target| target.name.clone())
                                    .unwrap_or_else(|| attachment_target_label(id)),
                            })
                            .collect();
                        element_nodes.push(ElementNode {
                            identifier: element.identifier.clone(),
                            name: element.name.clone(),
                            element_type: element.element_type.as_str().to_string(),
                            attachments,
                        });
                    }

                    file_nodes.push(FileNode {
                        name: file_name,
                        path: file_path_str.to_string(),
                        elements: element_nodes,
                    });
                }
            }

            folders.push(FolderNode {
                name: folder_path.clone(),
                path: folder_name.clone(),
                files: file_nodes,
            });
        }

        // Build relations
        let mut relations = Vec::new();
        let included_elements: HashSet<String> = filtered_elements;

        for element in self.registry.get_all_elements() {
            if !included_elements.contains(&element.identifier) {
                continue;
            }

            for relation in &element.relations {
                // Only include relations that should be shown in diagrams
                if !relation::DIAGRAM_RELATIONS.contains(&relation.relation_type.name) {
                    continue;
                }

                let (target_id, is_external) = match &relation.target.link {
                    relation::LinkType::Identifier(target_id) => {
                        if included_elements.contains(target_id) {
                            (target_id.clone(), false)
                        } else {
                            continue; // Skip relations to elements not in diagram
                        }
                    }
                    relation::LinkType::ExternalUrl(url) => (url.clone(), true),
                    relation::LinkType::InternalPath(path) => {
                        (path.to_string_lossy().to_string(), true)
                    }
                };

                if let Some(info) = relation::RELATION_TYPES.get(relation.relation_type.name) {
                    relations.push(ModelRelation {
                        source_id: element.identifier.clone(),
                        target_id,
                        target_label: relation.target.text.clone(),
                        relation_type: relation.relation_type.name.to_string(),
                        relation_label: info.label.to_string(),
                        arrow: info.arrow.to_string(),
                        is_external,
                    });
                }
            }
        }

        // Sort relations for deterministic output
        relations.sort_by(|a, b| {
            a.source_id
                .cmp(&b.source_id)
                .then_with(|| a.target_id.cmp(&b.target_id))
                .then_with(|| a.relation_type.cmp(&b.relation_type))
        });

        Ok(ModelDiagramReport { folders, relations })
    }

    /// Generate Mermaid diagram from model report
    pub fn generate_mermaid(&self, report: &ModelDiagramReport) -> String {
        let mut diagram = format!("```mermaid\ngraph {};\n", DEFAULT_DIAGRAM_DIRECTION);

        // Add auto-generation marker
        diagram.push_str(&format!("  %% {}\n", AUTOGEN_DIAGRAM_MARKER));

        // Define Mermaid graph styles with MBSE color scheme
        diagram.push_str("  %% Graph styling\n");
        diagram.push_str("  classDef capability fill:#BBDEFB,stroke:#1976D2,stroke-width:2.5px;\n");
        diagram.push_str(
            "  classDef systemRequirement fill:#E1D8EE,stroke:#673AB7,stroke-width:1.5px;\n",
        );
        diagram.push_str("  classDef ontology fill:#F4E3A1,stroke:#B08A00,stroke-width:2px;\n");
        diagram.push_str("  classDef verification fill:#DCEDC8,stroke:#4CAF50,stroke-width:2px;\n");
        diagram.push_str("  classDef folder fill:#FAFAFA,stroke:#9E9E9E,stroke-width:3px;\n");
        diagram.push_str("  classDef file fill:#FFF8E1,stroke:#FFCA28,stroke-width:2px;\n");
        diagram.push_str("  classDef attachment fill:#EFEBE9,stroke:#8D6E63,stroke-width:1.5px;\n");
        diagram.push_str("  classDef default fill:#F5F5F5,stroke:#424242,stroke-width:1.5px;\n\n");

        // Add folders, files, and elements
        for folder in &report.folders {
            let folder_id = utils::hash_identifier(&folder.path);
            diagram.push_str(&format!(
                "  subgraph {}[\"📁 {}\"]\n",
                folder_id,
                escape_label(&folder.name)
            ));

            for file in &folder.files {
                let file_id = utils::hash_identifier(&file.path);
                diagram.push_str(&format!(
                    "    subgraph {}[\"📄 {}\"]\n",
                    file_id,
                    escape_label(&file.name)
                ));

                for element in &file.elements {
                    let element_id = utils::hash_identifier(&element.identifier);

                    // Build label with element name and attachments
                    let mut label = escape_label(&element.name);
                    for attachment in &element.attachments {
                        label.push_str(&format!("<br/>📎 {}", escape_label(attachment)));
                    }

                    diagram.push_str(&format!("      {}[\"{}\"];\n", element_id, label));

                    // Determine element class based on type
                    let class = match element.element_type.as_str() {
                        "capability" => "capability",
                        "ontology" => "ontology",
                        "requirement" | "system-requirement" => "systemRequirement",
                        t if t.contains("verification") => "verification",
                        _ => "default",
                    };
                    diagram.push_str(&format!("      class {} {};\n", element_id, class));

                    // Add click link to element
                    diagram.push_str(&format!(
                        "      click {} \"{}\";\n",
                        element_id, element.identifier
                    ));
                }

                diagram.push_str("    end\n"); // end file
            }

            diagram.push_str("  end\n"); // end folder
        }

        // Add relations
        let mut added_external_nodes = HashSet::new();
        for relation in &report.relations {
            let source_id = utils::hash_identifier(&relation.source_id);
            let target_id = if relation.is_external {
                let target_hash = utils::hash_identifier(&relation.target_id);
                // Only add external node definition once
                if !added_external_nodes.contains(&target_hash) {
                    let label = escape_label(&relation.target_label);
                    diagram.push_str(&format!("  {}[\"{}\"];\n", target_hash, label));
                    diagram.push_str(&format!("  class {} default;\n", target_hash));
                    added_external_nodes.insert(target_hash.clone());
                }
                target_hash
            } else {
                utils::hash_identifier(&relation.target_id)
            };

            diagram.push_str(&format!(
                "  {} {}|{}| {};\n",
                source_id, relation.arrow, relation.relation_label, target_id,
            ));
        }

        diagram.push_str("```");
        diagram
    }

    /// Generate JSON from model report
    pub fn generate_json(&self, report: &ModelDiagramReport) -> Result<String, ReqvireError> {
        serde_json::to_string_pretty(report)
            .map_err(|e| ReqvireError::SerializationError(e.to_string()))
    }

    /// Generate Markdown text from model report
    pub fn generate_markdown(&self, report: &ModelDiagramReport) -> String {
        let mut markdown = String::new();

        for folder in &report.folders {
            markdown.push_str(&format!("## 📁 {}\n\n", folder.name));

            for file in &folder.files {
                markdown.push_str(&format!("### 📄 {}\n\n", file.name));

                for element in &file.elements {
                    markdown.push_str(&format!(
                        "- **{}** ({}): `{}`\n",
                        element.name, element.element_type, element.identifier
                    ));
                }

                markdown.push('\n');
            }
        }

        // Add relations section
        if !report.relations.is_empty() {
            markdown.push_str("## Relations\n\n");
            for relation in &report.relations {
                markdown.push_str(&format!(
                    "- `{}` {} `{}` ({})\n",
                    relation.source_id,
                    relation.relation_type,
                    if relation.is_external {
                        &relation.target_label
                    } else {
                        &relation.target_id
                    },
                    relation.relation_label
                ));
            }
        }

        markdown
    }
}

/// Generates diagrams grouped by `file_path` (one diagram per file)
/// Returns HashMap where key is file_path and value is the Mermaid diagram
pub fn generate_diagrams_by_file(
    registry: &GraphRegistry,
    diagrams_with_blobs: bool,
) -> Result<HashMap<String, String>, ReqvireError> {
    let mut diagrams: HashMap<String, String> = HashMap::new();

    // Group elements by file_path (one diagram per file)
    let mut grouped_elements: HashMap<String, Vec<&Element>> = HashMap::new();

    let elements = registry.get_all_elements();

    for element in elements {
        grouped_elements
            .entry(element.file_path.clone())
            .or_default()
            .push(element);
    }

    // Generate diagrams for each file
    for (file_path, file_elements) in grouped_elements {
        debug!("Generating diagram for file: {}", file_path);

        let diagram =
            generate_file_diagram(registry, &file_elements, &file_path, diagrams_with_blobs)?;
        diagrams.insert(file_path, diagram);
    }

    Ok(diagrams)
}

/// Generates a diagram for a single file with containment structure
fn generate_file_diagram(
    registry: &GraphRegistry,
    elements: &[&Element],
    file_path: &str,
    diagrams_with_blobs: bool,
) -> Result<String, ReqvireError> {
    use std::collections::HashMap;

    // Get Git repository information for creating proper links
    let repo_root = match git_commands::get_git_root_dir() {
        Ok(root) => root,
        Err(_) => PathBuf::from(""),
    };

    let base_url = git_commands::get_repository_base_url().unwrap_or_default();

    let commit_hash = match git_commands::get_commit_hash() {
        Ok(hash) => hash,
        Err(_) => String::from("HEAD"),
    };

    let has_git_info =
        !base_url.is_empty() && !commit_hash.is_empty() && !repo_root.as_os_str().is_empty();

    // Convert file path to its parent directory for relative links
    let base_dir = PathBuf::from(file_path)
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("."));

    // Collect identifiers of elements in this file
    let file_element_identifiers: HashSet<String> =
        elements.iter().map(|e| e.identifier.clone()).collect();

    // First pass: collect ALL elements that will be in the diagram
    let mut all_elements: Vec<&Element> = elements.to_vec();
    let mut included_ids: HashSet<String> = file_element_identifiers.clone();

    // Find all children of file-local elements even if they are in other files
    for file_element in elements {
        for relation in &file_element.relations {
            if !relation::DIAGRAM_RELATIONS.contains(&relation.relation_type.name) {
                continue;
            }
            if let relation::LinkType::Identifier(target_id) = &relation.target.link {
                if !included_ids.contains(target_id) {
                    if let Some(target_element) = registry.get_element(target_id) {
                        all_elements.push(target_element);
                        included_ids.insert(target_id.clone());
                    }
                }
            }
        }
    }

    // Group elements by folder -> file for containment structure
    let mut folders: HashMap<String, HashMap<String, Vec<&Element>>> = HashMap::new();

    for elem in &all_elements {
        let elem_file_path = &elem.file_path;
        let folder = PathBuf::from(elem_file_path)
            .parent()
            .and_then(|p| p.to_str())
            .unwrap_or("")
            .to_string();
        let file_name = PathBuf::from(elem_file_path)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(elem_file_path)
            .to_string();

        folders
            .entry(folder)
            .or_default()
            .entry(file_name)
            .or_default()
            .push(*elem);
    }

    // Use default diagram direction constant
    let mut diagram = format!("```mermaid\ngraph {};\n", DEFAULT_DIAGRAM_DIRECTION);

    // Add auto-generation marker for identification
    diagram.push_str(&format!("  %% {}\n", AUTOGEN_DIAGRAM_MARKER));

    // Define Mermaid graph styles
    diagram.push_str("  %% Graph styling\n");
    diagram.push_str("  classDef capability fill:#BBDEFB,stroke:#1976D2,stroke-width:2.5px;\n");
    diagram
        .push_str("  classDef systemRequirement fill:#E1D8EE,stroke:#673AB7,stroke-width:1.5px;\n");
    diagram.push_str("  classDef ontology fill:#F4E3A1,stroke:#B08A00,stroke-width:2px;\n");
    diagram.push_str("  classDef verification fill:#DCEDC8,stroke:#4CAF50,stroke-width:2px;\n");
    diagram.push_str("  classDef folder fill:#FAFAFA,stroke:#9E9E9E,stroke-width:3px;\n");
    diagram.push_str("  classDef file fill:#FFF8E1,stroke:#FFCA28,stroke-width:2px;\n");
    diagram.push_str("  classDef default fill:#F5F5F5,stroke:#424242,stroke-width:1.5px;\n\n");

    // Sort folders for deterministic output
    let mut folder_names: Vec<&String> = folders.keys().collect();
    folder_names.sort();

    // Generate subgraphs for folders and files (containment structure)
    for folder_name in folder_names {
        let files = &folders[folder_name];
        let folder_id = utils::hash_identifier(&format!("folder:{}", folder_name));
        let folder_display = if folder_name.is_empty() {
            "root"
        } else {
            folder_name
        };

        diagram.push_str(&format!(
            "  subgraph {}[\"📁 {}\"]\n",
            folder_id,
            escape_label(folder_display)
        ));

        // Sort files for deterministic output
        let mut file_names: Vec<&String> = files.keys().collect();
        file_names.sort();

        for file_name in file_names {
            let file_elements = &files[file_name];
            let file_id = utils::hash_identifier(&format!("file:{}:{}", folder_name, file_name));

            diagram.push_str(&format!(
                "    subgraph {}[\"📄 {}\"]\n",
                file_id,
                escape_label(file_name)
            ));

            // Sort elements for deterministic output
            let mut sorted_elements: Vec<&&Element> = file_elements.iter().collect();
            sorted_elements.sort_by(|a, b| a.identifier.cmp(&b.identifier));

            for elem in sorted_elements {
                let elem_id = utils::hash_identifier(&elem.identifier);

                // Build label with attachments
                let mut label = elem.name.replace('"', "&quot;");
                for attachment in &elem.attachments {
                    let attachment_name = match &attachment.target {
                        crate::element::AttachmentTarget::FilePath(path) => path
                            .file_name()
                            .map(|n| n.to_string_lossy().into_owned())
                            .unwrap_or_else(|| path.to_string_lossy().into_owned()),
                        crate::element::AttachmentTarget::ElementIdentifier(id) => registry
                            .get_element(id)
                            .map(|target| target.name.clone())
                            .unwrap_or_else(|| attachment_target_label(id)),
                    };
                    label.push_str(&format!("<br/>📎 {}", escape_label(&attachment_name)));
                }

                let class = match &elem.element_type {
                    ElementType::Capability => "capability",
                    ElementType::Ontology => "ontology",
                    ElementType::Requirement(RequirementType::System) => "systemRequirement",
                    ElementType::Verification(_) => "verification",
                    _ => "default",
                };

                // Get click target (relative or git blob URL)
                let click_target = get_element_click_target(
                    elem,
                    &base_dir,
                    diagrams_with_blobs,
                    has_git_info,
                    &base_url,
                    &commit_hash,
                )?;

                diagram.push_str(&format!("      {}[\"{}\"];\n", elem_id, label));
                diagram.push_str(&format!("      class {} {};\n", elem_id, class));
                diagram.push_str(&format!("      click {} \"{}\";\n", elem_id, click_target));
            }

            diagram.push_str("    end\n");
        }

        diagram.push_str("  end\n");
    }

    // Second pass: add all relations
    let mut rendered_relations: HashSet<String> = HashSet::new();

    for elem in &all_elements {
        let elem_id = utils::hash_identifier(&elem.identifier);

        // Sort relations for deterministic output
        let mut sorted_relations: Vec<_> = elem.relations.iter().collect();
        sorted_relations.sort_by(|a, b| {
            a.relation_type
                .name
                .cmp(b.relation_type.name)
                .then_with(|| match (&a.target.link, &b.target.link) {
                    (
                        relation::LinkType::Identifier(a_id),
                        relation::LinkType::Identifier(b_id),
                    ) => a_id.cmp(b_id),
                    (
                        relation::LinkType::ExternalUrl(a_url),
                        relation::LinkType::ExternalUrl(b_url),
                    ) => a_url.cmp(b_url),
                    (
                        relation::LinkType::InternalPath(a_path),
                        relation::LinkType::InternalPath(b_path),
                    ) => a_path.cmp(b_path),
                    _ => std::cmp::Ordering::Equal,
                })
        });

        for relation in sorted_relations {
            if !relation::DIAGRAM_RELATIONS.contains(&relation.relation_type.name) {
                continue;
            }

            let label = relation.target.text.clone();
            let (target_id, needs_node) = match &relation.target.link {
                relation::LinkType::Identifier(target) => {
                    (utils::hash_identifier(target), false) // Node already in subgraph
                }
                relation::LinkType::ExternalUrl(url) => (utils::hash_identifier(url), true),
                relation::LinkType::InternalPath(path) => {
                    let cow = path.to_string_lossy();
                    (utils::hash_identifier(cow.as_ref()), true)
                }
            };

            // Add external/file nodes that aren't in subgraphs
            if needs_node {
                let node_key = format!("node:{}", target_id);
                if !rendered_relations.contains(&node_key) {
                    rendered_relations.insert(node_key);

                    let click_target = match &relation.target.link {
                        relation::LinkType::ExternalUrl(url) => url.clone(),
                        relation::LinkType::InternalPath(path) => {
                            if diagrams_with_blobs && has_git_info {
                                let relative_id = match utils::get_relative_path(path) {
                                    Ok(rel_path) => rel_path.to_string_lossy().to_string(),
                                    Err(_) => path.to_string_lossy().to_string(),
                                };
                                format!("{}/blob/{}/{}", base_url, commit_hash, relative_id)
                            } else {
                                utils::to_relative_identifier(
                                    &path.to_string_lossy(),
                                    &base_dir,
                                    false,
                                )?
                            }
                        }
                        _ => String::new(),
                    };

                    diagram.push_str(&format!("  {}[\"{}\"];\n", target_id, label));
                    diagram.push_str(&format!("  class {} default;\n", target_id));
                    diagram.push_str(&format!("  click {} \"{}\";\n", target_id, click_target));
                }
            }

            // Add the relation edge
            if let Some(info) = relation::RELATION_TYPES.get(relation.relation_type.name) {
                let relation_key =
                    format!("{}->{}:{}", elem_id, target_id, relation.relation_type.name);
                if !rendered_relations.contains(&relation_key) {
                    rendered_relations.insert(relation_key);
                    diagram.push_str(&format!(
                        "  {} {}|{}| {};\n",
                        elem_id, info.arrow, info.label, target_id,
                    ));
                }
            }
        }
    }

    diagram.push_str("```");

    Ok(diagram)
}

/// Get click target URL for an element (relative path or git blob URL)
fn get_element_click_target(
    element: &Element,
    base_dir: &PathBuf,
    diagrams_with_blobs: bool,
    has_git_info: bool,
    base_url: &str,
    commit_hash: &str,
) -> Result<String, ReqvireError> {
    if diagrams_with_blobs && has_git_info {
        let relative_id = match utils::get_relative_path(&PathBuf::from(&element.identifier)) {
            Ok(rel_path) => rel_path.to_string_lossy().to_string(),
            Err(_) => element.identifier.clone(),
        };
        Ok(format!("{}/blob/{}/{}", base_url, commit_hash, relative_id))
    } else {
        utils::to_relative_identifier(&element.identifier, base_dir, false)
    }
}

/// Processes diagram generation for markdown files in place (without writing to output).
/// Used when the `--generate-diagrams` flag is set.
pub fn process_diagrams(
    registry: &GraphRegistry,
    diagrams_with_blobs: bool,
) -> Result<(), ReqvireError> {
    // Generate diagrams by file
    let diagrams = generate_diagrams_by_file(registry, diagrams_with_blobs)?;

    // Get git root for resolving relative paths
    let git_root = match git_commands::get_git_root_dir() {
        Ok(root) => root,
        Err(_) => {
            log::error!("Not in a git repository, using current directory");
            std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
        }
    };

    // Process each file
    for (file_path, new_diagram) in diagrams {
        // Resolve file path relative to git root, not current directory
        let absolute_file_path = git_root.join(&file_path);

        // Read file content
        let file_content = match filesystem::read_file(&absolute_file_path) {
            Ok(content) => content,
            Err(e) => {
                log::error!(
                    "Failed to read file '{}': {}",
                    absolute_file_path.display(),
                    e
                );
                continue;
            }
        };

        // Replace diagram in this file
        let updated_content = replace_file_diagram(&file_content, &new_diagram);

        // Write updated content back if modified
        if let Err(e) = filesystem::write_file(&absolute_file_path, &updated_content) {
            log::error!(
                "Failed to write updated diagrams to '{}': {}",
                absolute_file_path.display(),
                e
            );
        } else {
            info_println!("Updated diagrams in '{}'", file_path);
        }
    }

    Ok(())
}

/// Replaces the auto-generated diagram in a markdown file.
/// Inserts after the `# Elements` header.
///
/// - `content`: The original file content.
/// - `new_diagram`: The newly generated Mermaid diagram.
///
/// Returns the modified file content as a `String`.
fn replace_file_diagram(content: &str, new_diagram: &str) -> String {
    let requirements_header = "# Elements";
    let mermaid_block_start = "```mermaid";
    let mermaid_block_end = "```";

    let mut new_lines = Vec::new();
    let mut lines = content.lines().peekable();
    let mut found_requirements = false;

    while let Some(line) = lines.next() {
        if line.trim() == requirements_header && !found_requirements {
            found_requirements = true;
            new_lines.push(line.to_string());

            // Skip any blank lines immediately after the header
            while let Some(&next_line) = lines.peek() {
                if next_line.trim().is_empty() {
                    new_lines.push(lines.next().unwrap().to_string());
                } else {
                    break;
                }
            }

            // Check if the next non-empty line starts a Mermaid block
            if let Some(&next_line) = lines.peek() {
                if next_line.trim().starts_with(mermaid_block_start) {
                    // Found a mermaid block - collect it to check for autogen marker
                    let mut mermaid_lines = Vec::new();
                    mermaid_lines.push(lines.next().unwrap().to_string()); // mermaid start

                    let mut has_autogen_marker = false;
                    for l in lines.by_ref() {
                        if l.contains(AUTOGEN_DIAGRAM_MARKER) {
                            has_autogen_marker = true;
                        }
                        mermaid_lines.push(l.to_string());
                        if l.trim() == mermaid_block_end {
                            break;
                        }
                    }

                    // Only replace diagrams with the autogenerated marker
                    if has_autogen_marker {
                        new_lines.push(new_diagram.to_string());
                    } else {
                        // Preserve user-created diagrams
                        new_lines.extend(mermaid_lines);
                    }
                } else {
                    // No mermaid block exists, insert the new diagram
                    new_lines.push(new_diagram.to_string());
                }
            } else {
                // No content after header, insert the new diagram
                new_lines.push(new_diagram.to_string());
            }
        } else {
            new_lines.push(line.to_string());
        }
    }
    new_lines.join("\n")
}

/// Removes all auto-generated mermaid diagrams from a markdown file.
///
/// - `content`: The original file content.
///
/// Returns the modified file content as a `String`.
fn remove_file_diagrams(content: &str) -> String {
    let mermaid_block_start = "```mermaid";
    let mermaid_block_end = "```";

    let mut new_lines = Vec::new();
    let mut lines = content.lines().peekable();

    while let Some(line) = lines.next() {
        if line.trim().starts_with(mermaid_block_start) {
            // Found a mermaid block - collect it to check for autogen marker
            let mut mermaid_lines = Vec::new();
            mermaid_lines.push(line.to_string());

            let mut has_autogen_marker = false;
            for l in lines.by_ref() {
                if l.contains(AUTOGEN_DIAGRAM_MARKER) {
                    has_autogen_marker = true;
                }
                mermaid_lines.push(l.to_string());
                if l.trim() == mermaid_block_end {
                    break;
                }
            }

            // Only remove diagrams with the autogenerated marker
            if !has_autogen_marker {
                // Preserve user-created diagrams
                new_lines.extend(mermaid_lines);
            }
            // If it has autogen marker, we skip it (effectively removing it)
        } else {
            new_lines.push(line.to_string());
        }
    }
    new_lines.join("\n")
}

/// Remove all generated mermaid diagrams from markdown files
/// Follows the same pattern as process_diagrams but removes instead of replacing
pub fn remove_diagrams(registry: &GraphRegistry) -> Result<(), ReqvireError> {
    // Get unique file paths from elements
    let elements = registry.get_all_elements();
    let mut files_to_update: std::collections::HashSet<String> = std::collections::HashSet::new();

    for element in elements {
        files_to_update.insert(element.file_path.clone());
    }

    // Get git root for resolving relative paths
    let git_root = match git_commands::get_git_root_dir() {
        Ok(root) => root,
        Err(_) => {
            log::error!("Not in a git repository, using current directory");
            std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
        }
    };

    // Process each file
    for file_path in files_to_update {
        // Resolve file path relative to git root, not current directory
        let absolute_file_path = git_root.join(&file_path);

        // Read file content
        let file_content = match filesystem::read_file(&absolute_file_path) {
            Ok(content) => content,
            Err(e) => {
                log::error!(
                    "Failed to read file '{}': {}",
                    absolute_file_path.display(),
                    e
                );
                continue;
            }
        };

        // Remove all diagrams from this file
        let updated_content = remove_file_diagrams(&file_content);

        // Write updated content back if modified
        if let Err(e) = filesystem::write_file(&absolute_file_path, &updated_content) {
            log::error!(
                "Failed to write updated file '{}': {}",
                absolute_file_path.display(),
                e
            );
        } else {
            println!("Removed diagrams from '{}'", file_path);
        }
    }

    Ok(())
}

/// Generates a complete model diagram with containment hierarchy using Mermaid subgraphs
/// Shows folders > files > elements with relations
///
/// # Arguments
/// * `registry` - The graph registry containing all elements
/// * `root_element_id` - Optional element ID to generate diagram from. If None, generates full model.
///   If Some, generates diagram starting from that element and its related elements.
pub fn generate_model_diagram(
    registry: &GraphRegistry,
    root_element_id: Option<&str>,
) -> Result<String, ReqvireError> {
    let generator = ModelDiagramGenerator::new(registry, root_element_id);
    let report = generator.generate()?;
    Ok(generator.generate_mermaid(&report))
}

/// Generates a model diagram with optional filtering and output format selection
///
/// # Arguments
/// * `registry` - The graph registry containing all elements
/// * `root_element_id` - Optional element ID to filter from. If provided with forward_only=true, only includes forward-reachable elements
/// * `forward_only` - If true and root_element_id is provided, only traverses forward relations (derive, satisfiedBy, verifiedBy, trace)
/// * `json_output` - If true, returns JSON; otherwise returns markdown with embedded Mermaid diagram
pub fn generate_model_report(
    registry: &GraphRegistry,
    root_element_id: Option<&str>,
    forward_only: bool,
    json_output: bool,
) -> Result<String, ReqvireError> {
    let generator = ModelDiagramGenerator::new_with_mode(registry, root_element_id, forward_only);
    let report = generator.generate()?;

    if json_output {
        generator.generate_json(&report)
    } else {
        // Return markdown with embedded Mermaid diagram
        let mut output = generator.generate_markdown(&report);
        output.push_str("\n\n");
        output.push_str(&generator.generate_mermaid(&report));
        Ok(output)
    }
}

/// Collects all elements related to a root element by traversing the graph
/// This includes the root element and all elements it has relations to/from
fn collect_related_elements(registry: &GraphRegistry, root_id: &str) -> HashSet<String> {
    let mut result = HashSet::new();
    let mut to_visit = vec![root_id.to_string()];

    while let Some(current_id) = to_visit.pop() {
        if result.contains(&current_id) {
            continue;
        }
        result.insert(current_id.clone());

        if let Some(element) = registry.get_element(&current_id) {
            // Add all elements this element relates to
            for relation in &element.relations {
                if let relation::LinkType::Identifier(target_id) = &relation.target.link {
                    if !result.contains(target_id) {
                        to_visit.push(target_id.clone());
                    }
                }
            }

            // Also find elements that relate to this element
            for other_element in registry.get_all_elements() {
                if other_element.identifier == current_id {
                    continue;
                }

                for relation in &other_element.relations {
                    if let relation::LinkType::Identifier(target_id) = &relation.target.link {
                        if target_id == &current_id && !result.contains(&other_element.identifier) {
                            to_visit.push(other_element.identifier.clone());
                        }
                    }
                }
            }
        }
    }

    result
}

/// Collects all elements reachable from a root element by traversing only forward relations
/// This includes the root element and all elements reachable via DIAGRAM_RELATIONS (derive, satisfiedBy, verifiedBy, trace)
/// Does NOT traverse backward - only follows outgoing relations from each element
fn collect_forward_related_elements(registry: &GraphRegistry, root_id: &str) -> HashSet<String> {
    let mut result = HashSet::new();
    let mut to_visit = vec![root_id.to_string()];

    while let Some(current_id) = to_visit.pop() {
        if result.contains(&current_id) {
            continue;
        }
        result.insert(current_id.clone());

        if let Some(element) = registry.get_element(&current_id) {
            // Only add elements this element relates to (forward relations only)
            for relation in &element.relations {
                // Only follow forward relations shown in diagrams
                if !relation::DIAGRAM_RELATIONS.contains(&relation.relation_type.name) {
                    continue;
                }

                if let relation::LinkType::Identifier(target_id) = &relation.target.link {
                    if !result.contains(target_id) {
                        to_visit.push(target_id.clone());
                    }
                }
            }
            // NOTE: We do NOT traverse backward - only outgoing relations from each element
        }
    }

    result
}

/// Helper to group elements by file path, filtering to only include specified element IDs
fn group_elements_by_file_filtered<'a>(
    registry: &'a GraphRegistry,
    filter: &HashSet<String>,
) -> HashMap<String, Vec<&'a Element>> {
    let mut result: HashMap<String, Vec<&'a Element>> = HashMap::new();
    for element in registry.get_all_elements() {
        if filter.contains(&element.identifier) {
            result
                .entry(element.file_path.clone())
                .or_default()
                .push(element);
        }
    }
    result
}

/// Helper to group files by folder
fn group_files_by_folder(
    elements_by_file: &HashMap<String, Vec<&Element>>,
) -> HashMap<String, Vec<String>> {
    let mut result: HashMap<String, Vec<String>> = HashMap::new();
    for file_path in elements_by_file.keys() {
        let folder = Path::new(file_path)
            .parent()
            .and_then(|p| p.to_str())
            .unwrap_or("")
            .to_string();
        result.entry(folder).or_default().push(file_path.clone());
    }
    result
}

/// Escape special characters in labels for Mermaid
pub fn escape_label(text: &str) -> String {
    text.replace('"', "&quot;")
        .replace('[', "&#91;")
        .replace(']', "&#93;")
        .replace('(', "&#40;")
        .replace(')', "&#41;")
}

fn attachment_target_label(target: &str) -> String {
    let fragment_or_path = target.rsplit('#').next().unwrap_or(target);
    let basename = fragment_or_path
        .rsplit('/')
        .next()
        .unwrap_or(fragment_or_path);
    if basename.is_empty() {
        target.to_string()
    } else {
        basename.to_string()
    }
}

/// Generate containment view diagram showing folder/file/element hierarchy
///
/// When `short` is true, shows only root elements (those without hierarchical parents).
/// When `short` is false (default), shows all elements.
pub fn generate_containment_diagram(
    registry: &GraphRegistry,
    short: bool,
) -> Result<String, ReqvireError> {
    // Build containment hierarchy structure
    let hierarchy = crate::containment::ContainmentHierarchy::build(registry, short)?;

    let mut output = String::new();

    // Note about element display mode
    if short {
        output.push_str("*Elements filtered to show only root elements (those without hierarchical parent relations within the same file).*\n\n");
    }
    output.push_str("```mermaid\n");
    output.push_str("graph TD\n");

    // CSS class definitions
    output.push_str("  %% Graph styling\n");
    output.push_str("  classDef capability fill:#BBDEFB,stroke:#1976D2,stroke-width:2.5px;\n");
    output
        .push_str("  classDef systemRequirement fill:#E1D8EE,stroke:#673AB7,stroke-width:1.5px;\n");
    output.push_str("  classDef requirement fill:#ECEFF1,stroke:#673AB7,stroke-width:1.5px;\n");
    output.push_str("  classDef ontology fill:#F4E3A1,stroke:#B08A00,stroke-width:2px;\n");
    output.push_str("  classDef verification fill:#DCEDC8,stroke:#4CAF50,stroke-width:2px;\n");
    output.push_str("  classDef default fill:#F5F5F5,stroke:#424242,stroke-width:1.5px;\n");
    output.push_str("  classDef folder fill:#FAFAFA,stroke:#9E9E9E,stroke-width:2px;\n");
    output.push_str("  classDef file fill:#FFF8E1,stroke:#FFCA28,stroke-width:2px;\n");
    output.push_str("  classDef attachment fill:#EFEBE9,stroke:#8D6E63,stroke-width:1.5px;\n\n");

    // Define root node
    output.push_str("  root[\"📁 Reqvire root\"]\n");
    output.push_str("  class root folder\n\n");

    // Generate tree structure from hierarchy
    generate_folder_tree(&hierarchy.root_folder, "root", &mut output)?;
    output.push('\n');

    // Collect all elements for styling and links
    let all_elements = collect_all_elements(&hierarchy.root_folder);
    let all_design_docs = collect_all_design_documents(&hierarchy.root_folder);

    // Generate element styling
    output.push_str("  %% Element type styling\n");
    for element in &all_elements {
        let hash_id = generate_element_hash(&element.identifier);
        let class_name = get_element_class_from_type(&element.element_type);
        output.push_str(&format!("  class {} {}\n", hash_id, class_name));
    }

    // Generate clickable links
    output.push_str("\n  %% Clickable links\n");
    // Design documents first
    for doc in &all_design_docs {
        let doc_id = sanitize_design_doc_id(&doc.path);
        output.push_str(&format!("  click {} \"{}\"\n", doc_id, doc.path));
    }
    // Elements
    for element in &all_elements {
        let hash_id = generate_element_hash(&element.identifier);
        let fragment = element.identifier.split('#').nth(1).unwrap_or("");
        output.push_str(&format!(
            "  click {} \"{}#{}\"\n",
            hash_id, element.file_path, fragment
        ));
    }

    output.push_str("```\n");

    Ok(output)
}

/// Generate folder tree structure recursively using containment hierarchy
fn generate_folder_tree(
    folder: &crate::containment::ContainmentFolder,
    parent_id: &str,
    output: &mut String,
) -> Result<(), ReqvireError> {
    // Generate subfolders
    for subfolder in &folder.subfolders {
        let folder_id = sanitize_folder_id(&subfolder.path);
        output.push_str(&format!("  {}[\"📁 {}\"]\n", folder_id, subfolder.name));
        output.push_str(&format!("  {} --> {}\n", parent_id, folder_id));
        output.push_str(&format!("  class {} folder\n", folder_id));

        // Recursively generate subfolder contents
        generate_folder_tree(subfolder, &folder_id, output)?;
    }

    // Generate design documents
    for doc in &folder.design_documents {
        let doc_id = sanitize_design_doc_id(&doc.path);
        output.push_str(&format!("  {}[\"📝 {}\"]\n", doc_id, doc.name));
        output.push_str(&format!("  {} --> {}\n", parent_id, doc_id));
        output.push_str(&format!("  class {} attachment\n", doc_id));
    }

    // Generate files
    for file in &folder.files {
        let file_id = sanitize_file_id(&file.path);

        // Create subgraph for file containing elements
        output.push_str(&format!("  subgraph {}[\"📄 {}\"]\n", file_id, file.name));
        output.push_str("    direction TB\n");

        // Generate element nodes with attachments
        for element in &file.elements {
            let hash_id = generate_element_hash(&element.identifier);
            let mut label = escape_label(&element.name);
            // Add attachments to label
            for attachment in &element.attachments {
                label.push_str(&format!("<br/>📎 {}", escape_label(&attachment.name)));
            }
            output.push_str(&format!("    {}[\"{}\"]\n", hash_id, label));
        }

        output.push_str("  end\n");
        output.push_str(&format!("  {} --> {}\n", parent_id, file_id));
    }

    Ok(())
}

/// Collect all elements from folder hierarchy for styling and links
fn collect_all_elements(
    folder: &crate::containment::ContainmentFolder,
) -> Vec<crate::containment::ContainmentElement> {
    let mut elements = Vec::new();

    // Collect from files in this folder
    for file in &folder.files {
        elements.extend(file.elements.clone());
    }

    // Recursively collect from subfolders
    for subfolder in &folder.subfolders {
        elements.extend(collect_all_elements(subfolder));
    }

    // Sort for deterministic output
    elements.sort_by(|a, b| a.identifier.cmp(&b.identifier));

    elements
}

/// Collect all design documents from folder hierarchy for click links
fn collect_all_design_documents(
    folder: &crate::containment::ContainmentFolder,
) -> Vec<crate::containment::DesignDocument> {
    let mut docs = Vec::new();

    // Collect from this folder
    docs.extend(folder.design_documents.clone());

    // Recursively collect from subfolders
    for subfolder in &folder.subfolders {
        docs.extend(collect_all_design_documents(subfolder));
    }

    // Sort for deterministic output
    docs.sort_by(|a, b| a.path.cmp(&b.path));

    docs
}

fn sanitize_folder_id(path: &[String]) -> String {
    path.join("_")
        .replace(".", "")
        .replace("-", "_")
        .replace(" ", "_")
}

fn sanitize_file_id(name: &str) -> String {
    name.replace(".md", "")
        .replace(".", "")
        .replace("-", "_")
        .replace(" ", "_")
}

fn sanitize_design_doc_id(path: &str) -> String {
    path.replace("/", "_")
        .replace(".md", "")
        .replace(".", "")
        .replace("-", "_")
        .replace(" ", "_")
}

fn generate_element_hash(identifier: &str) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut hasher = DefaultHasher::new();
    identifier.hash(&mut hasher);
    let hash = hasher.finish();
    format!("{:016x}", hash)
}

fn get_element_class_from_type(element_type: &ElementType) -> &'static str {
    match element_type {
        ElementType::Capability => "capability",
        ElementType::Ontology => "ontology",
        ElementType::Requirement(RequirementType::System) => "systemRequirement",
        ElementType::Verification(_) => "verification",
        _ => "default",
    }
}

/// Generate containment view as D3.js collapsible tree
///
/// Generates a markdown code block with `d3-tree` language containing JSON data
/// that can be rendered as an interactive collapsible tree in HTML export.
///
/// When `short` is true, shows only root elements (those without hierarchical parents).
/// When `short` is false (default), shows all elements.
pub fn generate_containment_d3_tree(
    registry: &GraphRegistry,
    short: bool,
) -> Result<String, ReqvireError> {
    // Build containment hierarchy structure
    let hierarchy = crate::containment::ContainmentHierarchy::build(registry, short)?;

    // Convert to D3 tree format
    let d3_tree = hierarchy.to_d3_tree();

    // Serialize to JSON
    let json = serde_json::to_string_pretty(&d3_tree).map_err(|e| {
        ReqvireError::SerializationError(format!("Failed to serialize D3 tree: {}", e))
    })?;

    let mut output = String::new();

    // Note about element display mode
    if short {
        output.push_str("*Elements filtered to show only root elements (those without hierarchical parent relations within the same file).*\n\n");
    }

    // Output as d3-tree code block
    output.push_str("```d3-tree\n");
    output.push_str(&json);
    output.push_str("\n```\n");

    Ok(output)
}

/// Generate containment view as D3.js sunburst diagram
///
/// Generates a markdown code block with `d3-sunburst` language containing JSON data
/// that can be rendered as an interactive sunburst diagram in HTML export.
///
/// Uses the same hierarchical JSON format as the D3 tree.
pub fn generate_containment_d3_sunburst(
    registry: &GraphRegistry,
    short: bool,
) -> Result<String, ReqvireError> {
    // Build containment hierarchy structure
    let hierarchy = crate::containment::ContainmentHierarchy::build(registry, short)?;

    // Convert to D3 tree format (same format works for sunburst)
    let d3_tree = hierarchy.to_d3_tree();

    // Serialize to JSON
    let json = serde_json::to_string_pretty(&d3_tree).map_err(|e| {
        ReqvireError::SerializationError(format!("Failed to serialize D3 sunburst: {}", e))
    })?;

    let mut output = String::new();

    // Note about element display mode
    if short {
        output.push_str("*Elements filtered to show only root elements (those without hierarchical parent relations within the same file).*\n\n");
    }

    // Output as d3-sunburst code block
    output.push_str("```d3-sunburst\n");
    output.push_str(&json);
    output.push_str("\n```\n");

    Ok(output)
}

/// Generate D3.js icicle/partition diagram for containment view
pub fn generate_containment_d3_icicle(
    registry: &GraphRegistry,
    short: bool,
) -> Result<String, ReqvireError> {
    // Build containment hierarchy structure (same as sunburst/tree)
    let hierarchy = crate::containment::ContainmentHierarchy::build(registry, short)?;

    // Convert to D3 tree format (works for icicle too)
    let d3_tree = hierarchy.to_d3_tree();

    // Serialize to JSON
    let json = serde_json::to_string_pretty(&d3_tree).map_err(|e| {
        ReqvireError::SerializationError(format!("Failed to serialize D3 icicle: {}", e))
    })?;

    let mut output = String::new();

    if short {
        output.push_str("*Elements filtered to show only root elements (those without hierarchical parent relations within the same file).*\n\n");
    }

    // Output as d3-icicle code block
    output.push_str("```d3-icicle\n");
    output.push_str(&json);
    output.push_str("\n```\n");

    Ok(output)
}
