#!/bin/bash
set -euo pipefail

# Create log file immediately to ensure it exists for runner
echo "Starting test..." > "${TEST_DIR}/test_results.log"

# Test: Diagram Removal Functionality (Marker-Based)
# ----------------------------------------------------
# Acceptance Criteria:
# - System should remove all auto-generated mermaid diagrams identified by REQVIRE-AUTOGENERATED-DIAGRAM marker
# - System should preserve custom mermaid diagrams that do not contain the marker
# - System should handle files with multiple diagrams correctly, removing only marked ones
# - System should work on files without any diagrams
# - Marker-based identification should work regardless of diagram location in document
#
# Test Criteria:
# - Command exits with success (0) return code
# - Auto-generated diagrams containing REQVIRE-AUTOGENERATED-DIAGRAM marker are removed
# - Custom diagrams without marker are preserved regardless of location
# - File structure remains intact except for diagram removal

# Use existing reqvire.yaml configuration

# Make backup copies of original files for comparison
mkdir -p "$TEST_DIR/backup"
cp -r "$TEST_DIR/specifications" "$TEST_DIR/backup/"

# First, ensure we have diagrams to remove by generating them (validation happens automatically)
echo "Running: reqvire generate-diagrams (setup)" >> "${TEST_DIR}/test_results.log"
set +e
GENERATE_OUTPUT=$(cd "$TEST_DIR" && "$REQVIRE_BIN" --config "$TEST_DIR/reqvire.yaml" generate-diagrams 2>&1)
GENERATE_EXIT_CODE=$?
set -e

echo "Exit code: $GENERATE_EXIT_CODE" >> "${TEST_DIR}/test_results.log"
printf "%s\n" "$GENERATE_OUTPUT" >> "${TEST_DIR}/test_results.log"

if [ $GENERATE_EXIT_CODE -ne 0 ]; then
  echo "❌ FAILED: Initial diagram generation failed:"
  echo "$GENERATE_OUTPUT"
  exit 1
fi

# Verify diagrams were generated
if ! grep -q '```mermaid' "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: No mermaid diagrams found after generation"
  exit 1
fi

# Test: Verify that generated diagrams contain the marker
if ! grep -A 10 '```mermaid' "$TEST_DIR/specifications/Requirements.md" | grep -q 'REQVIRE-AUTOGENERATED-DIAGRAM'; then
  echo "❌ FAILED: Generated diagrams do not contain REQVIRE-AUTOGENERATED-DIAGRAM marker"
  exit 1
fi

# Test: Verify that custom diagram does NOT contain the marker
CUSTOM_DIAGRAM_SECTION=$(sed -n '/Custom Diagram/,/```$/p' "$TEST_DIR/specifications/Requirements.md")
if echo "$CUSTOM_DIAGRAM_SECTION" | grep -q 'REQVIRE-AUTOGENERATED-DIAGRAM'; then
  echo "❌ FAILED: Custom diagram should not contain REQVIRE-AUTOGENERATED-DIAGRAM marker"
  exit 1
fi

# Count the number of mermaid diagrams before removal
BEFORE_COUNT=$(grep -c '```mermaid' "$TEST_DIR/specifications/Requirements.md")

# Run reqvire to remove diagrams
echo "Running: reqvire remove-diagrams" >> "${TEST_DIR}/test_results.log"
set +e
OUTPUT=$(cd "$TEST_DIR" && "$REQVIRE_BIN" --config "$TEST_DIR/reqvire.yaml" remove-diagrams 2>&1)
EXIT_CODE=$?
set -e

echo "Exit code: $EXIT_CODE" >> "${TEST_DIR}/test_results.log"
printf "%s\n" "$OUTPUT" >> "${TEST_DIR}/test_results.log"

# Check for basic success
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ FAILED: remove-diagrams command failed with exit code $EXIT_CODE"
  echo "$OUTPUT"
  exit 1
fi

# Verify diagrams were removed
AFTER_COUNT=$(grep -c '```mermaid' "$TEST_DIR/specifications/Requirements.md" 2>/dev/null)
if [ $? -ne 0 ]; then
    AFTER_COUNT=0
fi

# Test 1: Check that auto-generated diagrams were removed but custom diagrams preserved
# We expect 1 custom diagram to remain after removing the auto-generated ones
EXPECTED_REMAINING=1
if [ "$AFTER_COUNT" -ne "$EXPECTED_REMAINING" ]; then
  echo "❌ FAILED: Expected $EXPECTED_REMAINING diagram remaining (custom), but found $AFTER_COUNT"
  exit 1
fi

# Test 1.1: Verify that the remaining diagram is indeed the custom one (without marker)
REMAINING_DIAGRAM_SECTION=$(grep -A 10 '```mermaid' "$TEST_DIR/specifications/Requirements.md")
if echo "$REMAINING_DIAGRAM_SECTION" | grep -q 'REQVIRE-AUTOGENERATED-DIAGRAM'; then
  echo "❌ FAILED: Remaining diagram contains marker - should only be custom diagrams left"
  exit 1
fi

# Test 1.2: Verify that the custom diagram content is preserved
if ! echo "$REMAINING_DIAGRAM_SECTION" | grep -q 'Custom Diagram'; then
  echo "❌ FAILED: Custom diagram content not found in remaining diagram"
  exit 1
fi

# Test 2: Check that the file still exists and has the requirements
if [ ! -f "$TEST_DIR/specifications/Requirements.md" ]; then
  echo "❌ FAILED: Requirements file was deleted"
  exit 1
fi

# Test 3: Verify that requirement text is still present
if ! grep -q "Test Requirement" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Requirement text was removed"
  exit 1
fi

if ! grep -q "Another Requirement" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Second requirement text was removed"
  exit 1
fi

# Test 4: Check that section headers are preserved
if ! grep -q "## Test Section" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Section headers were removed"
  exit 1
fi

if ! grep -q "## Another Section" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Second section header was removed"
  exit 1
fi

# Test 5: Verify that element headers are preserved
if ! grep -q "### Test Requirement" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Element headers were removed"
  exit 1
fi

# Test 6: Check command output for success indicators
if ! echo "$OUTPUT" | grep -q -i "diagram"; then
  echo "❌ FAILED: Output does not mention diagrams"
  exit 1
fi

# Test 7: Verify that diagrams in excluded files are preserved
IGNORED_FILE_DIAGRAMS=$(grep -c '```mermaid' "$TEST_DIR/specifications/IgnoredFile.md" 2>/dev/null)
if [ $? -ne 0 ]; then
    IGNORED_FILE_DIAGRAMS=0
fi
if [ "$IGNORED_FILE_DIAGRAMS" -ne 2 ]; then
  echo "❌ FAILED: Expected 2 diagrams in ignored file, but found $IGNORED_FILE_DIAGRAMS"
  exit 1
fi

# Verify the content of ignored diagrams is intact
if ! grep -q "Ignored Diagram" "$TEST_DIR/specifications/IgnoredFile.md"; then
  echo "❌ FAILED: Content in ignored file was modified"
  exit 1
fi

if ! grep -q "Another Ignored Diagram" "$TEST_DIR/specifications/IgnoredFile.md"; then
  echo "❌ FAILED: Second diagram in ignored file was modified"
  exit 1
fi

# Clean up backup directory
rm -rf "$TEST_DIR/backup"

exit 0