#!/bin/bash
set -uo pipefail

TEST_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create log file immediately to ensure it exists for runner
echo "Starting test..." > "${TEST_DIR}/test_results.log"

# Test: Diagram Removal Functionality (Marker-Based)
# ----------------------------------------------------
# Acceptance Criteria:
# - System should remove all auto-generated mermaid diagrams identified by REQVIRE-AUTOGENERATED-DIAGRAM marker
# - System should preserve custom mermaid diagrams that do not contain the marker
# - System should handle files with multiple diagrams correctly, removing only marked ones
# - System should work on files without any diagrams
# - Marker-based identification should work regardless of diagram location in document
#
# Test Criteria:
# - Command exits with success (0) return code
# - Auto-generated diagrams containing REQVIRE-AUTOGENERATED-DIAGRAM marker are removed
# - Custom diagrams without marker are preserved regardless of location
# - File structure remains intact except for diagram removal

# Helper function to compare files and show diff on failure
assert_file_matches() {
  local expected="$1"
  local actual="$2"
  local description="$3"

  if ! diff -u "$expected" "$actual"; then
    echo "❌ FAILED: $description"
    echo ""
    echo "If changes are intentional, update the expected file:"
    echo "  cp $actual $expected"
    exit 1
  fi
}

# First, ensure we have diagrams to remove by generating them (validation happens automatically)
echo "Running: reqvire generate-diagrams (setup)" >> "${TEST_DIR}/test_results.log"
set +e
GENERATE_OUTPUT=$(cd "$TEST_DIR" && "$REQVIRE_BIN" generate-diagrams 2>&1)
GENERATE_EXIT_CODE=$?
set -e

echo "Exit code: $GENERATE_EXIT_CODE" >> "${TEST_DIR}/test_results.log"
printf "%s\n" "$GENERATE_OUTPUT" >> "${TEST_DIR}/test_results.log"

if [ $GENERATE_EXIT_CODE -ne 0 ]; then
  echo "❌ FAILED: Initial diagram generation failed:"
  echo "$GENERATE_OUTPUT"
  exit 1
fi

# Run reqvire to remove diagrams
echo "Running: reqvire remove-diagrams" >> "${TEST_DIR}/test_results.log"
set +e
OUTPUT=$(cd "$TEST_DIR" && "$REQVIRE_BIN" remove-diagrams 2>&1)
EXIT_CODE=$?
set -e

echo "Exit code: $EXIT_CODE" >> "${TEST_DIR}/test_results.log"
printf "%s\n" "$OUTPUT" >> "${TEST_DIR}/test_results.log"

# Check for basic success
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ FAILED: remove-diagrams command failed with exit code $EXIT_CODE"
  echo "$OUTPUT"
  exit 1
fi

# Compare final output against expected files
assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/Requirements-after-remove.md" \
  "$TEST_DIR/specifications/Requirements.md" \
  "Requirements.md after diagram removal does not match expected"

assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/IgnoredFile-after-remove.md" \
  "$TEST_DIR/specifications/IgnoredFile.md" \
  "IgnoredFile.md should be unchanged (excluded from processing)"

exit 0
