use crate::element::{Element, SubSection, ElementType, RequirementType, Attachment, AttachmentTarget};
use crate::relation::Relation;
use crate::error::ReqvireError;
use crate::utils;
use log::debug;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

/// Removes only auto-generated mermaid diagrams from content
/// Preserves user-created diagrams by checking for the REQVIRE-AUTOGENERATED-DIAGRAM marker
fn remove_generated_diagrams(content: &str) -> String {
    let mut result = String::new();
    let mut lines = content.lines();

    while let Some(line) = lines.next() {
        if line.trim().starts_with("```mermaid") {
            // Collect the entire mermaid block to check if it's auto-generated
            let mut block_lines = vec![line];
            let mut is_auto_generated = false;

            // Read until the closing ```
            while let Some(block_line) = lines.next() {
                block_lines.push(block_line);

                if block_line.contains("REQVIRE-AUTOGENERATED-DIAGRAM") {
                    is_auto_generated = true;
                }

                if block_line.trim() == "```" {
                    break;
                }
            }

            // Only include the block if it's NOT auto-generated (preserve user diagrams)
            if !is_auto_generated {
                for block_line in block_lines {
                    result.push_str(block_line);
                    result.push('\n');
                }
            }
        } else {
            result.push_str(line);
            result.push('\n');
        }
    }

    result
}

/// Parses a single element from markdown string.
/// Used for CRUD operations (add command) to parse element from stdin or inline argument.
/// Returns the parsed Element or an error.
pub fn parse_single_element(
    content: &str,
    file_path: &str,
) -> Result<Element, ReqvireError> {
    let mut current_element: Option<Element> = None;
    let mut current_subsection = SubSection::Other("".to_string());
    let mut seen_subsections = HashSet::new();
    let mut in_details_block = false;
    let mut found_header = false;

    for (line_num, line) in content.lines().enumerate() {
        let trimmed = line.trim();

        // Handle <details> blocks
        if in_details_block {
            if let Some(element) = &mut current_element {
                element.add_content(&format!("{}\n", line));
            }
            if trimmed.starts_with("</details>") {
                in_details_block = false;
            }
            continue;
        }

        // Separator line ends the element
        if trimmed == "---" {
            break;
        }

        // Parse ### header (element name)
        if trimmed.starts_with("### ") {
            if found_header {
                return Err(ReqvireError::InvalidMarkdownStructure(
                    "Multiple ### headers found. Single element should have only one ### header.".to_string()
                ));
            }

            found_header = true;
            current_subsection = SubSection::Requirement;

            let element_name = trimmed[4..].trim().to_string();

            // file_path is already relative to git root, use it directly
            // Only normalize the fragment part (element name)
            let normalized_fragment = utils::normalize_fragment(&element_name);
            let normalized_id = format!("{}#{}", file_path, normalized_fragment);

            // Default element type is always 'requirement' (location-independent)
            let element_type = ElementType::Requirement(RequirementType::System);

            let new_element = Element::new(
                &element_name,
                &normalized_id,
                file_path,  // Already relative
                line_num + 1,
                Some(element_type),
            );

            current_element = Some(new_element);

        // Parse #### subsections
        } else if trimmed.starts_with("#### ") && current_element.is_some() {
            let subsection = SubSection::from_str(&trimmed[5..].trim());

            if seen_subsections.contains(&subsection) {
                return Err(ReqvireError::DuplicateSubsection(
                    format!("Duplicate subsection '{}'", subsection.name())
                ));
            }
            seen_subsections.insert(subsection.clone());

            // If transitioning to Details subsection, add the header to content
            if subsection == SubSection::Details {
                if let Some(element) = &mut current_element {
                    element.add_content("\n#### Details\n");
                }
            }

            current_subsection = subsection;

        // Handle level 5+ headers
        } else if trimmed.starts_with("#####") && current_element.is_some() && current_subsection != SubSection::Details {
            return Err(ReqvireError::InvalidMarkdownStructure(
                "Level 5+ headers (#####+) can only appear inside '#### Details' subsection".to_string()
            ));

        // Parse content for Requirement or Details subsections
        } else if current_subsection == SubSection::Requirement || current_subsection == SubSection::Details {
            if let Some(element) = &mut current_element {
                if trimmed.starts_with("<details") {
                    in_details_block = true;
                }
                element.add_content(&format!("{}\n", line));
            }

        // Parse metadata
        } else if current_subsection == SubSection::Metadata {
            if trimmed.is_empty() {
                continue;
            }
            if let Some(element) = &mut current_element {
                if let Some((key, value)) = utils::parse_metadata_line(trimmed) {
                    element.metadata.insert(key.clone(), value.clone());

                    if key.eq_ignore_ascii_case("type") {
                        element.set_type_from_metadata();
                    }
                } else {
                    return Err(ReqvireError::InvalidMetadataFormat(
                        format!("Invalid metadata format: '{}'", trimmed)
                    ));
                }
            }

        // Parse relations
        } else if current_subsection == SubSection::Relations {
            if let Some(element) = &mut current_element {
                if trimmed.starts_with("* ") {
                    let (relation_type, (text, link)) = utils::parse_relation_line(trimmed)
                        .map_err(|_| ReqvireError::InvalidRelationFormat(
                            format!("Invalid relation format: '{}'", trimmed)
                        ))?;

                    // Normalize relation target
                    // file_path is already relative to git root (e.g., "specifications/NewFile.md")
                    let git_root = crate::git_commands::get_git_root_dir()?;

                    let normalized_target = if link.starts_with('#') {
                        // Same-file reference: just prepend file_path (already git-root-relative)
                        format!("{}{}", file_path, link)
                    } else {
                        // External file reference: normalize relative to the target file's directory
                        // Get the directory of the target file as base path for normalization
                        let file_parent = Path::new(file_path)
                            .parent()
                            .ok_or_else(|| ReqvireError::PathError(
                                format!("Cannot determine parent directory of '{}'", file_path)
                            ))?;
                        let base_path = git_root.join(file_parent);

                        utils::normalize_identifier(&link, &base_path)?
                    };

                    let relation = Relation::new(&relation_type, text, &normalized_target, None)?;
                    element.add_relation(relation);

                } else if !trimmed.is_empty() {
                    return Err(ReqvireError::InvalidRelationFormat(
                        format!("Invalid relations format: '{}'", trimmed)
                    ));
                }
            }

        // Parse attachments
        } else if current_subsection == SubSection::Attachments {
            if let Some(element) = &mut current_element {
                if trimmed.starts_with("* ") || trimmed.starts_with("- ") {
                    match utils::parse_attachment_line(trimmed) {
                        Ok(href) => {
                            // Determine if this is an element identifier or file path
                            let target = if href.contains('#') {
                                // Element identifier - use same normalization as relations
                                let git_root = crate::git_commands::get_git_root_dir()?;
                                let normalized = if href.starts_with('#') {
                                    // Same-file reference: just prepend file_path
                                    format!("{}{}", file_path, href)
                                } else {
                                    // Cross-file reference: normalize relative to file's directory
                                    let file_parent = Path::new(file_path)
                                        .parent()
                                        .ok_or_else(|| ReqvireError::PathError(
                                            format!("Cannot determine parent directory of '{}'", file_path)
                                        ))?;
                                    let base_path = git_root.join(file_parent);
                                    utils::normalize_identifier(&href, &base_path)?
                                };
                                AttachmentTarget::ElementIdentifier(normalized)
                            } else {
                                // File path - resolve to git-root-relative
                                let git_root = crate::git_commands::get_git_root_dir()?;
                                let git_root_path = git_root.join(&href);
                                let attachment_path = if git_root_path.exists() {
                                    PathBuf::from(&href)
                                } else {
                                    // Try file-relative path
                                    let file_parent = Path::new(file_path)
                                        .parent()
                                        .unwrap_or_else(|| Path::new("."));
                                    let resolved = file_parent.join(&href);
                                    // Normalize path
                                    let mut normalized = PathBuf::new();
                                    for component in resolved.components() {
                                        match component {
                                            std::path::Component::ParentDir => { normalized.pop(); }
                                            std::path::Component::CurDir => { /* skip */ }
                                            _ => { normalized.push(component); }
                                        }
                                    }
                                    normalized
                                };
                                AttachmentTarget::FilePath(attachment_path)
                            };
                            element.attachments.push(Attachment { target, content_hash: None });
                        }
                        Err(e) => {
                            return Err(ReqvireError::InvalidAttachmentFormat(
                                format!("Invalid attachment format '{}': {}", trimmed, e)
                            ));
                        }
                    }
                } else if !trimmed.is_empty() {
                    return Err(ReqvireError::InvalidAttachmentFormat(
                        format!("Invalid attachment format: '{}'", trimmed)
                    ));
                }
            }
        }
    }

    // Finalize element
    if let Some(mut element) = current_element {
        if !found_header {
            return Err(ReqvireError::InvalidMarkdownStructure(
                "Element must start with ### header".to_string()
            ));
        }
        element.freeze_content();
        Ok(element)
    } else {
        Err(ReqvireError::InvalidMarkdownStructure(
            "No element found in markdown string".to_string()
        ))
    }
}

/// Checks if the file is a specification file by looking for "# Elements" as first H1 heading.
/// Returns true if file should be parsed, false if it should be skipped.
fn is_specification_file(content: &str) -> bool {
    for line in content.lines() {
        let trimmed = line.trim();
        // Skip empty lines and non-heading content before first H1
        if trimmed.is_empty() {
            continue;
        }
        // Check if this is an H1 heading
        if trimmed.starts_with("# ") {
            // First H1 heading found - check if it's "# Elements"
            return trimmed == "# Elements";
        }
        // If we hit any other H1 or content that's not a heading, keep looking
        // (allow frontmatter, comments, etc. before the heading)
        if !trimmed.starts_with('#') && !trimmed.starts_with("---") && !trimmed.starts_with("<!--") {
            // Non-header, non-frontmatter content before H1 - skip but continue looking
            continue;
        }
    }
    // No H1 heading found
    false
}

/// Parses a markdown document and extracts elements with metadata and relations.
/// Returns: (elements, errors, page_content)
/// Only parses files where the first H1 heading is "# Elements".
/// If git_commit is Some, file attachment hashes are computed from the git commit, not working directory.
pub fn parse_elements(
    file: &str,
    content: &str,
    file_path: &PathBuf,
    git_commit: Option<&str>,
) -> (Vec<Element>, Vec<ReqvireError>, String) {
    // Check if this is a specification file (first H1 must be "# Elements")
    if !is_specification_file(content) {
        debug!("Skipping file {} - not a specification file (no '# Elements' heading)", file);
        return (Vec::new(), Vec::new(), String::new());
    }

    let mut elements = Vec::new();
    let mut current_element: Option<Element> = None;
    let mut errors = Vec::new();
    let mut seen_identifiers = HashSet::new();
    let mut skip_current_element = false;
    let mut seen_subsections = HashSet::new();
    let mut in_details_block = false;


    let mut current_subsection = SubSection::Other("".to_string());

    // Content tracking variables
    let mut page_content = String::new();

    // File element order tracking
    let mut file_element_counter: usize = 0;

    for (line_num, line) in content.lines().enumerate() {
        let trimmed = line.trim();


        if in_details_block {
            if !skip_current_element {
                if let Some(element) = &mut current_element {
                    element.add_content(&format!("{}\n", line));
                }
            }
        
            if trimmed.starts_with("</details>") {
                in_details_block = false;
            }
        
            continue; // Skip any further processing while in <details>        

        }else if trimmed == "---" {
            current_subsection = SubSection::Other("".to_string());

        } else if trimmed.starts_with("<details") {
            // Start of details block - set flag and add content if in element
            in_details_block = true;
            if let Some(element) = &mut current_element {
                if !skip_current_element {
                    element.add_content(&format!("{}\n", line));
                }
            }
            continue;

        } else if trimmed.starts_with("## ") {
            // Section headers (## ) are not allowed - report syntax error
            let section_name = trimmed[3..].trim();
            errors.push(ReqvireError::InvalidMarkdownStructure(format!(
                "Section headers (## ) are not allowed in specification files. Found '## {}' at line {} in file '{}'. Use ### for element headers instead.",
                section_name,
                line_num + 1,
                file_path.display()
            )));
            continue;

        } else if trimmed.starts_with("### ") {
            current_subsection = SubSection::Requirement;

            if let Some(mut element) = current_element.take() {
                if !skip_current_element {
                    element.freeze_content();
                    elements.push(element);
                }
            }

            skip_current_element = false;
            seen_subsections.clear();

            let element_name = trimmed[4..].trim().to_string();

            match file_path.parent() {
                Some(file_folder) => {
                    let identifier = format!("{}#{}", file, element_name);

                    match utils::normalize_identifier(
                        &identifier,
                        &file_folder.to_path_buf()
                    ) {
                        Ok(identifier) => {
                        
                            let relative_file = match utils::get_relative_path(&file_path) {
                                Ok(path) => path,
                                Err(err) => {
                                    debug!("Error: {}", &err);
                                    skip_current_element = true;
                                    errors.push(err);
                                    continue;
                                }
                            };

                            seen_identifiers.insert(identifier.clone());

                            // Default element type is always 'requirement' (location-independent)
                            let element_type = ElementType::Requirement(RequirementType::System);

                            let mut new_element = Element::new(
                                &element_name,
                                &identifier,
                                &relative_file.to_string_lossy(),
                                line_num + 1, // line_number is 1-indexed
                                Some(element_type),
                            );

                            // Set file order index
                            new_element.file_order_index = file_element_counter;
                            file_element_counter += 1;

                            current_element = Some(new_element);
                            debug!("Found element: {}", element_name);
                        }
                        Err(e) => {
                            let msg = format!(
                                "Failed to normalize identifier for '{}': {} (file: {}, line {})",
                                element_name,
                                e,
                                file_path.display(),
                                line_num + 1
                            );
                            errors.push(ReqvireError::InvalidIdentifier(msg.clone()));
                            debug!("Error: {}", msg);
                            skip_current_element = true;
                        }
                    }
                }
                None => {
                    let msg = format!(
                        "Failed to normalize identifier for '{}': {} (file: {}, line {})",
                        element_name,
                        "File folder not accessible.",
                        file_path.display(),
                        line_num + 1
                    );
                    errors.push(ReqvireError::InvalidIdentifier(msg.clone()));
                    debug!("Error: {}", msg);
                    skip_current_element = true;
                }
            }

        } else if trimmed.starts_with("#####") && current_element.is_some() && current_subsection != SubSection::Details && !skip_current_element {
            // Level 5+ headers are only allowed inside Details subsection
            let msg = format!(
                "Invalid header level in element '{}': Level 5+ headers (#####+) can only appear inside '#### Details' subsection (file: {}, line {})",
                current_element.as_ref().unwrap().name,
                file_path.display(),
                line_num + 1
            );
            errors.push(ReqvireError::InvalidMarkdownStructure(msg.clone()));
            debug!("Error: {}", msg);

        } else if trimmed.starts_with("#### ") && current_element.is_some() {
            let subsection = SubSection::from_str(&trimmed[5..].trim());

            if !skip_current_element {
                if seen_subsections.contains(&subsection) {
                    let msg = format!(
                        "Duplicate subsection '{}' in element '{}' (file: {}, line {})",
                        subsection.name(),
                        current_element.as_ref().unwrap().name,
                        file_path.display(),
                        line_num + 1
                    );
                    errors.push(ReqvireError::DuplicateSubsection(msg.clone()));
                    debug!("Error: {}", msg);
                } else {
                    seen_subsections.insert(subsection.clone());
                }
            }

            // If transitioning to Details or non-reserved subsection, add the header to content
            if !skip_current_element {
                if let Some(element) = &mut current_element {
                    if subsection == SubSection::Details || matches!(subsection, SubSection::Other(_)) {
                        element.add_content(&format!("\n{}\n", line));
                    }
                }
            }

            current_subsection = subsection;

        } else if (current_subsection == SubSection::Requirement
            || current_subsection == SubSection::Details
            || matches!(current_subsection, SubSection::Other(_)))
            && current_element.is_some()
            && !skip_current_element
        {
            if let Some(element) = &mut current_element {
                if trimmed.starts_with("<details") {
                    in_details_block = true;
                }

                element.add_content(&format!("{}\n", line));

            }

        } else if in_details_block && !skip_current_element {
            // Still inside <details> block under 'Details' subsection
            if let Some(element) = &mut current_element {
                element.add_content(&format!("{}\n", line));
            }

        } else if current_subsection == SubSection::Metadata && !skip_current_element {
            if trimmed.is_empty() {
                continue;
            }
            if let Some(element) = &mut current_element {
                if let Some((key, value)) = utils::parse_metadata_line(trimmed) {
                    element.metadata.insert(key.clone(), value.clone());

                    if key.eq_ignore_ascii_case("type") {
                        element.set_type_from_metadata();
                    }
                } else {
                    let msg = format!(
                        "Element '{}' has invalid metadata format: '{}' (file: {}, line {})",
                        element.name, trimmed, file, line_num + 1
                    );
                    errors.push(ReqvireError::InvalidMetadataFormat(msg.clone()));
                    debug!("Error: {}", msg);
                    current_subsection = SubSection::Other("".to_string());
                }
            }

        } else if current_subsection == SubSection::Relations && !skip_current_element {
            if let Some(element) = &mut current_element {
                if trimmed.starts_with("* ") {
                    match utils::parse_relation_line(trimmed) {
                        Ok((relation_type, (text, link))) => {
                            let final_link = if link.starts_with('#') {
                                format!("{}{}", file, link)
                            } else {
                                link
                            };

                            match file_path.parent() {
                                Some(file_folder) => {
                                    match utils::normalize_identifier(
                                        &final_link,
                                        &file_folder.to_path_buf()
                                    ) {
                                        Ok(normalized_target) => {
                                            // element_id will be populated later by GraphRegistry after all elements are registered
                                            match Relation::new(&relation_type, text, &normalized_target, None) {
                                                Ok(relation) => {
                                                    element.add_relation(relation);
                                                }
                                                Err(_) => {
                                                    let msg = format!(
                                                        "'{}' in element '{}': (file: {}, line {})",
                                                        relation_type, element.name, file, line_num + 1
                                                    );
                                                    errors.push(ReqvireError::UnsupportedRelationType(msg.clone()));
                                                    debug!("Error: {}", msg);
                                                }
                                            }
                                        }
                                        Err(e) => {
                                            let msg = format!(
                                                "Failed to normalize identifier for '{}': {} (file: {}, line {})",
                                                element.name, e, file, line_num + 1
                                            );
                                            errors.push(ReqvireError::InvalidIdentifier(msg.clone()));
                                            debug!("Error: {}", msg);
                                        }
                                    }
                                }
                                None => {
                                    let msg = format!(
                                        "Failed to normalize identifier for '{}': {} (file: {}, line {})",
                                        trimmed,
                                        "File folder not accessible.",
                                        file_path.display(),
                                        line_num + 1
                                    );
                                    errors.push(ReqvireError::InvalidIdentifier(msg.clone()));
                                    debug!("Error: {}", msg);
                                }
                            }
                        }
                        Err(_) => {
                            let msg = format!(
                                "Element '{}' has invalid relation format: '{}'. (file: {}, line {})",
                                element.name, trimmed, file, line_num + 1
                            );
                            errors.push(ReqvireError::UnsupportedRelationType(msg.clone()));
                            debug!("Error: {}", msg);
                        }
                    }
                } else if trimmed.is_empty() {
                    // Ignore
                } else {
                    let msg = format!(
                        "Element '{}' has invalid relations format: '{}' (file: {}, line {})",
                        element.name, trimmed, file, line_num + 1
                    );
                    errors.push(ReqvireError::InvalidRelationFormat(msg.clone()));
                    debug!("Error: {}", msg);
                    current_subsection = SubSection::Other("".to_string());
                }
            }

        } else if current_subsection == SubSection::Attachments && !skip_current_element {
            // Parse Attachments subsection
            // Format: * [text](path) where path can be:
            // - File path (file-relative or git-root-relative)
            // - Element identifier (contains # and points to a Refinement element)
            if let Some(element) = &mut current_element {
                if trimmed.starts_with("* ") || trimmed.starts_with("- ") {
                    match utils::parse_attachment_line(trimmed) {
                        Ok(href) => {
                            // Determine if this is an element identifier or file path
                            // Element identifiers contain '#' (e.g., "File.md#element-name" or "#element-name")
                            let (target, content_hash): (AttachmentTarget, Option<String>) = if href.contains('#') {
                                // This is an element identifier - normalize it like relation targets
                                // For same-file references (starting with #), prepend current file path
                                let href_to_normalize = if href.starts_with('#') {
                                    format!("{}{}", file, href)
                                } else {
                                    href.clone()
                                };
                                let file_dir = file_path
                                    .parent()
                                    .unwrap_or_else(|| Path::new("."))
                                    .to_path_buf();
                                match utils::normalize_identifier(&href_to_normalize, &file_dir) {
                                    Ok(normalized) => (AttachmentTarget::ElementIdentifier(normalized), None),
                                    Err(e) => {
                                        let msg = format!(
                                            "Invalid attachment identifier in element '{}': {} (file: {}, line {})",
                                            element.name, e, file, line_num + 1
                                        );
                                        errors.push(ReqvireError::InvalidAttachmentFormat(msg.clone()));
                                        debug!("Error: {}", msg);
                                        continue;
                                    }
                                }
                            } else {
                                // This is a file path - resolve to git-root-relative
                                let git_root = crate::git_commands::get_git_root_dir()
                                    .unwrap_or_else(|_| PathBuf::from("."));

                                // First, check if path exists as git-root-relative
                                let git_root_path = git_root.join(&href);
                                let attachment_path = if git_root_path.exists() {
                                    // Path is git-root-relative (e.g., docs/SLA.txt)
                                    PathBuf::from(&href)
                                } else {
                                    // Try file-relative path
                                    let file_dir = file_path
                                        .parent()
                                        .unwrap_or_else(|| Path::new("."));
                                    let resolved = file_dir.join(&href);

                                    // Normalize path by resolving .. and . components
                                    let mut normalized = PathBuf::new();
                                    for component in resolved.components() {
                                        match component {
                                            std::path::Component::ParentDir => { normalized.pop(); }
                                            std::path::Component::CurDir => { /* skip */ }
                                            _ => { normalized.push(component); }
                                        }
                                    }

                                    // Strip git root to get git-root-relative path
                                    normalized.strip_prefix(&git_root)
                                        .map(|p| p.to_path_buf())
                                        .unwrap_or(normalized)
                                };

                                // Compute content_hash for file attachment
                                // If parsing from a git commit, read file from commit; otherwise from working directory
                                let full_path = git_root.join(&attachment_path);
                                let file_hash = if let Some(commit) = git_commit {
                                    // Read from git commit
                                    match crate::git_commands::get_file_at_commit(
                                        &full_path.to_string_lossy(),
                                        &git_root,
                                        commit
                                    ) {
                                        Ok(content) => Some(crate::utils::hash_content(&content)),
                                        Err(_) => None, // File doesn't exist in commit
                                    }
                                } else if full_path.exists() {
                                    // Read from working directory
                                    match std::fs::read_to_string(&full_path) {
                                        Ok(content) => Some(crate::utils::hash_content(&content)),
                                        Err(_) => {
                                            // Binary file or read error - hash the raw bytes
                                            match std::fs::read(&full_path) {
                                                Ok(bytes) => {
                                                    use std::hash::{Hash, Hasher};
                                                    let mut hasher = rustc_hash::FxHasher::default();
                                                    bytes.hash(&mut hasher);
                                                    Some(format!("{:x}", hasher.finish()))
                                                }
                                                Err(_) => None,
                                            }
                                        }
                                    }
                                } else {
                                    None // File doesn't exist yet
                                };

                                (AttachmentTarget::FilePath(attachment_path), file_hash)
                            };

                            // Check for duplicates
                            if !element.attachments.iter().any(|a| a.target == target) {
                                element.attachments.push(Attachment { target, content_hash });
                            } else {
                                let msg = format!(
                                    "Duplicate attachment '{}' in element '{}' (file: {}, line {})",
                                    href, element.name, file, line_num + 1
                                );
                                errors.push(ReqvireError::DuplicateAttachment(msg.clone()));
                                debug!("Warning: {}", msg);
                            }
                        }
                        Err(e) => {
                            let msg = format!(
                                "Invalid attachment in element '{}': {} (file: {}, line {})",
                                element.name, e, file, line_num + 1
                            );
                            errors.push(ReqvireError::InvalidAttachmentFormat(msg.clone()));
                            debug!("Error: {}", msg);
                        }
                    }
                } else if !trimmed.is_empty() {
                    // Non-empty line that's not a bullet point - end of Attachments subsection
                    current_subsection = SubSection::Other("".to_string());
                }
                // Empty lines are ignored within Attachments subsection
            }

        } else if matches!(current_subsection, SubSection::Other(_)) {
            // Accumulate page content: everything outside of elements, but skip the # Elements title
            if !trimmed.starts_with("# ") {
                page_content.push_str(line);
                page_content.push('\n');
            }
        }
    }

    // Final element
    if let Some(mut element) = current_element.take() {
        if !skip_current_element {
            element.freeze_content();
            elements.push(element);
        }
    }

    // Clean page content
    let cleaned_page_content = remove_generated_diagrams(&page_content);

    (elements, errors, cleaned_page_content.trim().to_string())
}


