/*
 * Compact dev fixture seed.
 *
 * Used ONLY in `npm run dev` (import.meta.env.DEV) when no served Project Store
 * seed is available, so the component shell is browsable during frontend work.
 * It keeps enough graph structure to exercise navigation, selection,
 * rollover focus, and detail panes. It is never shipped in release assets.
 */
import type { ExplorerProjectStore } from "./types";
import { EXPECTED_SCHEMA_VERSION } from "./types";

export const devFixture: ExplorerProjectStore = {
  schema_version: EXPECTED_SCHEMA_VERSION,
  project: {
    name: "reqvire",
    root_label: "reqvire @ dev-fixture",
    repository: "reqvire",
    branch: "dev-fixture",
  },
  folders: [
    {
      path: "system-model",
      parent: null,
      children: [
        "system-model/Capabilities",
        "system-model/Requirements",
        "system-model/Contracts",
        "system-model/Verifications",
        "system-model/Ontologies",
        "system-model/Thesaurus",
        "system-model/Evidence",
        "system-model/Specifications.md",
      ],
    },
    { path: "system-model/Capabilities", parent: "system-model", children: ["system-model/Capabilities/API.md"] },
    { path: "system-model/Requirements", parent: "system-model", children: ["system-model/Requirements/API.md"] },
    { path: "system-model/Contracts", parent: "system-model", children: ["system-model/Contracts/API.md"] },
    { path: "system-model/Verifications", parent: "system-model", children: ["system-model/Verifications/API.md"] },
    { path: "system-model/Ontologies", parent: "system-model", children: ["system-model/Ontologies/API.md"] },
    { path: "system-model/Thesaurus", parent: "system-model", children: ["system-model/Thesaurus/Thesaurus.md"] },
    { path: "system-model/Evidence", parent: "system-model", children: ["system-model/Evidence/api-smoke-report.json", "system-model/Evidence/openapi-fragment.yaml"] },
  ],
  files: [
    {
      path: "system-model/Capabilities/API.md",
      display_path: "system-model/Capabilities/API.md",
      markdown_content: [
        "# API Capability",
        "",
        "### API Exploration Capability",
        "",
        "The system can expose and explore API-facing model context.",
        "",
        "#### Metadata",
        "  * type: capability",
      ].join("\n"),
      parent_folder: "system-model/Capabilities",
      element_ids: ["system-model/Capabilities/API.md#api-exploration-capability"],
      resource_ids: [],
    },
    {
      path: "system-model/Requirements/API.md",
      display_path: "system-model/Requirements/API.md",
      markdown_content: [
        "# API Requirements",
        "",
        "### API Surface Exploration",
        "",
        "The Explorer shall show requirements, contracts, verifications, concepts, and evidence in one navigable project model.",
        "",
        "#### Metadata",
        "  * type: requirement",
        "",
        "### API Evidence Traceability",
        "",
        "The Explorer shall expose implementation and evidence files that satisfy verification work.",
        "",
        "#### Metadata",
        "  * type: requirement",
      ].join("\n"),
      parent_folder: "system-model/Requirements",
      element_ids: [
        "system-model/Requirements/API.md#api-surface-exploration",
        "system-model/Requirements/API.md#api-evidence-traceability",
      ],
      resource_ids: [],
    },
    {
      path: "system-model/Contracts/API.md",
      display_path: "system-model/Contracts/API.md",
      markdown_content: [
        "# API Contracts",
        "",
        "### API Response Contract",
        "",
        "API responses must expose stable identifiers, status, and error payload structure.",
        "",
        "#### Metadata",
        "  * type: specification",
      ].join("\n"),
      parent_folder: "system-model/Contracts",
      element_ids: ["system-model/Contracts/API.md#api-response-contract"],
      resource_ids: [],
    },
    {
      path: "system-model/Verifications/API.md",
      display_path: "system-model/Verifications/API.md",
      markdown_content: [
        "# API Verifications",
        "",
        "### API Verification Objective",
        "",
        "Verification objective for API Explorer fixture behavior.",
        "",
        "#### Metadata",
        "  * type: verification-objective",
        "",
        "### API Smoke Test Verification",
        "",
        "A smoke test checks the API exploration requirement.",
        "",
        "#### Metadata",
        "  * type: test-verification",
        "",
        "### API Contract Analysis",
        "",
        "An analysis verifies API contract coverage using exported evidence.",
        "",
        "#### Metadata",
        "  * type: analysis-verification",
      ].join("\n"),
      parent_folder: "system-model/Verifications",
      element_ids: [
        "system-model/Verifications/API.md#api-verification-objective",
        "system-model/Verifications/API.md#api-smoke-test-verification",
        "system-model/Verifications/API.md#api-contract-analysis",
      ],
      resource_ids: [],
    },
    {
      path: "system-model/Ontologies/API.md",
      display_path: "system-model/Ontologies/API.md",
      markdown_content: [
        "# API Ontology",
        "",
        "### API Runtime Ontology",
        "",
        "Structural API vocabulary used by the mock ontology graph.",
        "",
        "#### Metadata",
        "  * type: ontology",
        "",
        "### API Shape Contract",
        "",
        "SHACL shape contract for API surface vocabulary.",
        "",
        "#### Metadata",
        "  * type: semantic-contract",
      ].join("\n"),
      parent_folder: "system-model/Ontologies",
      element_ids: [
        "system-model/Ontologies/API.md#api-runtime-ontology",
        "system-model/Ontologies/API.md#api-shape-contract",
      ],
      resource_ids: [],
    },
    {
      path: "system-model/Thesaurus/Thesaurus.md",
      display_path: "system-model/Thesaurus/Thesaurus.md",
      markdown_content: [
        "# Thesaurus",
        "",
        "### Fixture Concepts",
        "",
        "Concept scheme for Explorer fixture terminology.",
        "",
        "#### Metadata",
        "  * type: concept-scheme",
        "",
        "### Verification Coverage",
        "",
        "Concept for verification coverage navigation.",
        "",
        "#### Metadata",
        "  * type: concept",
      ].join("\n"),
      parent_folder: "system-model/Ontologies",
      element_ids: [
        "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        "system-model/Specifications.md#verification-coverage",
      ],
      resource_ids: [],
    },
    {
      path: "system-model/Evidence/api-smoke-report.json",
      display_path: "system-model/Evidence/api-smoke-report.json",
      markdown_content: "{\n  \"status\": \"passed\",\n  \"checks\": [\"endpoint\", \"payload\", \"error-response\"]\n}\n",
      parent_folder: "system-model/Evidence",
      element_ids: [],
      resource_ids: ["resource:system-model/Evidence/api-smoke-report.json"],
    },
    {
      path: "system-model/Evidence/openapi-fragment.yaml",
      display_path: "system-model/Evidence/openapi-fragment.yaml",
      markdown_content: "paths:\n  /fixture:\n    get:\n      operationId: getFixture\n",
      parent_folder: "system-model/Evidence",
      element_ids: [],
      resource_ids: ["resource:system-model/Evidence/openapi-fragment.yaml"],
    },
    {
      path: "system-model/Specifications.md",
      display_path: "system-model/Specifications.md",
      markdown_content: [
        "# Elements",
        "",
        "### Example Requirement",
        "",
        "The dev fixture shall render Markdown inside the Explorer.",
        "",
        "#### Metadata",
        "  * type: requirement",
      ].join("\n"),
      parent_folder: "system-model",
      element_ids: [
        "system-model/Specifications.md#example-capability",
        "system-model/Specifications.md#example-requirement",
        "system-model/Specifications.md#example-unverified-requirement",
        "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        "system-model/Specifications.md#verification-coverage",
        "system-model/Specifications.md#example-verification",
        "system-model/Specifications.md#example-unsatisfied-verification",
      ],
      resource_ids: [],
    },
  ],
  resources: [
    {
      id: "resource:system-model/Evidence/api-smoke-report.json",
      kind: "local-file",
      target: "system-model/Evidence/api-smoke-report.json",
      display: "api-smoke-report.json",
      file_path: "system-model/Evidence/api-smoke-report.json",
      source_text: "{\n  \"status\": \"passed\",\n  \"checks\": [\"endpoint\", \"payload\", \"error-response\"]\n}\n",
      external_url: null,
      referring_element_ids: ["system-model/Verifications/API.md#api-smoke-test-verification"],
      relation_types: ["satisfiedBy"],
    },
    {
      id: "resource:system-model/Evidence/openapi-fragment.yaml",
      kind: "local-file",
      target: "system-model/Evidence/openapi-fragment.yaml",
      display: "openapi-fragment.yaml",
      file_path: "system-model/Evidence/openapi-fragment.yaml",
      source_text: "paths:\n  /fixture:\n    get:\n      operationId: getFixture\n",
      external_url: null,
      referring_element_ids: ["system-model/Verifications/API.md#api-contract-analysis"],
      relation_types: ["satisfiedBy"],
    },
    {
      id: "resource:crates/reqvire-core/src/lib.rs",
      kind: "local-file",
      target: "crates/reqvire-core/src/lib.rs",
      display: "lib.rs",
      file_path: "crates/reqvire-core/src/lib.rs",
      source_text: "pub fn fixture_source() -> &'static str {\n    \"ok\"\n}\n",
      external_url: null,
      referring_element_ids: ["system-model/Specifications.md#example-requirement"],
      relation_types: ["satisfiedBy"],
    },
  ],
  elements: [
    {
      id: "system-model/Capabilities/API.md#api-exploration-capability",
      name: "API Exploration Capability",
      element_type: "capability",
      type_family: "capability",
      file_path: "system-model/Capabilities/API.md",
      line_number: 3,
      source_anchor: "#/content/system-model/Capabilities/API.md#api-exploration-capability",
      content: "The system can expose and explore API-facing model context.",
      metadata: { type: "capability" },
      governance: { status: "draft" },
    },
    {
      id: "system-model/Requirements/API.md#api-surface-exploration",
      name: "API Surface Exploration",
      element_type: "requirement",
      type_family: "requirement",
      file_path: "system-model/Requirements/API.md",
      line_number: 3,
      source_anchor: "#/content/system-model/Requirements/API.md#api-surface-exploration",
      content: "The Explorer shall show requirements, contracts, verifications, concepts, and evidence in one navigable project model.",
      metadata: { type: "requirement" },
      governance: { status: "draft" },
    },
    {
      id: "system-model/Requirements/API.md#api-evidence-traceability",
      name: "API Evidence Traceability",
      element_type: "requirement",
      type_family: "requirement",
      file_path: "system-model/Requirements/API.md",
      line_number: 11,
      source_anchor: "#/content/system-model/Requirements/API.md#api-evidence-traceability",
      content: "The Explorer shall expose implementation and evidence files that satisfy verification work.",
      metadata: { type: "requirement" },
      governance: { status: "draft" },
    },
    {
      id: "system-model/Contracts/API.md#api-response-contract",
      name: "API Response Contract",
      element_type: "specification",
      type_family: "contract",
      file_path: "system-model/Contracts/API.md",
      line_number: 3,
      source_anchor: "#/content/system-model/Contracts/API.md#api-response-contract",
      content: "API responses must expose stable identifiers, status, and error payload structure.",
      metadata: { type: "specification" },
      governance: {},
    },
    {
      id: "system-model/Verifications/API.md#api-verification-objective",
      name: "API Verification Objective",
      element_type: "verification-objective",
      type_family: "verification",
      file_path: "system-model/Verifications/API.md",
      line_number: 3,
      source_anchor: "#/content/system-model/Verifications/API.md#api-verification-objective",
      content: "Verification objective for API Explorer fixture behavior.",
      metadata: { type: "verification-objective" },
      governance: {},
    },
    {
      id: "system-model/Verifications/API.md#api-smoke-test-verification",
      name: "API Smoke Test Verification",
      element_type: "test-verification",
      type_family: "verification",
      file_path: "system-model/Verifications/API.md",
      line_number: 11,
      source_anchor: "#/content/system-model/Verifications/API.md#api-smoke-test-verification",
      content: "A smoke test checks the API exploration requirement.",
      metadata: { type: "test-verification" },
      governance: {},
    },
    {
      id: "system-model/Verifications/API.md#api-contract-analysis",
      name: "API Contract Analysis",
      element_type: "analysis-verification",
      type_family: "verification",
      file_path: "system-model/Verifications/API.md",
      line_number: 19,
      source_anchor: "#/content/system-model/Verifications/API.md#api-contract-analysis",
      content: "An analysis verifies API contract coverage using exported evidence.",
      metadata: { type: "analysis-verification" },
      governance: {},
    },
    {
      id: "system-model/Ontologies/API.md#api-runtime-ontology",
      name: "API Runtime Ontology",
      element_type: "ontology",
      type_family: "ontology",
      file_path: "system-model/Ontologies/API.md",
      line_number: 3,
      source_anchor: "#/content/system-model/Ontologies/API.md#api-runtime-ontology",
      content: "Structural API vocabulary used by the mock ontology graph.",
      metadata: { type: "ontology" },
      governance: {},
    },
    {
      id: "system-model/Ontologies/API.md#api-shape-contract",
      name: "API Shape Contract",
      element_type: "semantic-contract",
      type_family: "semantic-contract",
      file_path: "system-model/Ontologies/API.md",
      line_number: 11,
      source_anchor: "#/content/system-model/Ontologies/API.md#api-shape-contract",
      content: "SHACL shape contract for API surface vocabulary.",
      metadata: { type: "semantic-contract" },
      governance: {},
    },
    {
      id: "system-model/Specifications.md#example-capability",
      name: "Example Capability",
      element_type: "capability",
      type_family: "capability",
      file_path: "system-model/Specifications.md",
      line_number: 1,
      source_anchor: "#/content/system-model/Specifications.md#example-capability",
      content: "The dev fixture shall expose a capability with mixed verification and implementation coverage.",
      metadata: { type: "capability" },
      governance: { status: "draft" },
    },
    {
      id: "system-model/Specifications.md#example-requirement",
      name: "Example Requirement",
      element_type: "requirement",
      type_family: "requirement",
      file_path: "system-model/Specifications.md",
      line_number: 3,
      source_anchor: "#/content/system-model/Specifications.md#example-requirement",
      content: "The system shall demonstrate the Explorer shell with fixture data.",
      metadata: { type: "requirement" },
      governance: { status: "draft" },
    },
    {
      id: "system-model/Specifications.md#example-unverified-requirement",
      name: "Unverified Fixture Requirement",
      element_type: "requirement",
      type_family: "requirement",
      file_path: "system-model/Specifications.md",
      line_number: 12,
      source_anchor: "#/content/system-model/Specifications.md#example-unverified-requirement",
      content: "The system shall demonstrate an uncovered requirement row in the Coverage view.",
      metadata: { type: "requirement" },
      governance: { status: "draft" },
    },
    {
      id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
      name: "Example Thesaurus",
      element_type: "concept-scheme",
      type_family: "concept-scheme",
      file_path: "system-model/Thesaurus/Thesaurus.md",
      line_number: 60,
      source_anchor: "#/content/system-model/Thesaurus/Thesaurus.md#fixture-concepts",
      content: "Fixture concept scheme for Explorer Thesaurus development.",
      metadata: {
        type: "concept-scheme",
        concept_base: "https://example.test/concepts",
        concept_prefix: "concept",
      },
      governance: {},
    },
    {
      id: "system-model/Thesaurus/Thesaurus.md#api-surface",
      name: "API Surface",
      element_type: "concept",
      type_family: "concept",
      file_path: "system-model/Thesaurus/Thesaurus.md",
      line_number: 64,
      source_anchor: "#/content/system-model/Thesaurus/Thesaurus.md#api-surface",
      content: "Curated terminology for public API endpoints, operations, and payload boundaries.",
      metadata: { type: "concept" },
      governance: {},
    },
    {
      id: "system-model/Thesaurus/Thesaurus.md#service-endpoint",
      name: "Service Endpoint",
      element_type: "concept",
      type_family: "concept",
      file_path: "system-model/Thesaurus/Thesaurus.md",
      line_number: 70,
      source_anchor: "#/content/system-model/Thesaurus/Thesaurus.md#service-endpoint",
      content: "A callable service boundary exposed by the system API.",
      metadata: { type: "concept" },
      governance: {},
    },
    {
      id: "system-model/Thesaurus/Thesaurus.md#traceability",
      name: "Traceability",
      element_type: "concept",
      type_family: "concept",
      file_path: "system-model/Thesaurus/Thesaurus.md",
      line_number: 80,
      source_anchor: "#/content/system-model/Thesaurus/Thesaurus.md#traceability",
      content: "The ability to follow model intent from capabilities through requirements, contracts, verification, and implementation evidence.",
      metadata: { type: "concept" },
      governance: {},
    },
    {
      id: "system-model/Specifications.md#verification-coverage",
      name: "Verification Coverage",
      element_type: "concept",
      type_family: "concept",
      file_path: "system-model/Specifications.md",
      line_number: 24,
      source_anchor: "#/content/system-model/Specifications.md#verification-coverage",
      content: "Closing verification obligations through tests, proofs, analyses, inspections, or demonstrations.",
      metadata: { type: "concept" },
      governance: {},
    },
    {
      id: "system-model/Specifications.md#example-verification",
      name: "Example Verification",
      element_type: "test-verification",
      type_family: "verification",
      file_path: "system-model/Specifications.md",
      line_number: 20,
      source_anchor: "#/content/system-model/Specifications.md#example-verification",
      content: "Verifies the Example Requirement via a test.",
      metadata: { type: "test-verification" },
      governance: {},
    },
    {
      id: "system-model/Specifications.md#example-unsatisfied-verification",
      name: "Unsatisfied Fixture Verification",
      element_type: "test-verification",
      type_family: "verification",
      file_path: "system-model/Specifications.md",
      line_number: 28,
      source_anchor: "#/content/system-model/Specifications.md#example-unsatisfied-verification",
      content: "Demonstrates a verification with no satisfiedBy evidence and no verified target.",
      metadata: { type: "test-verification" },
      governance: {},
    },
  ],
  relations: [
    {
      id: "rel:api:0",
      source_id: "system-model/Requirements/API.md#api-surface-exploration",
      target_id: "system-model/Capabilities/API.md#api-exploration-capability",
      target_kind: "element",
      relation_type: "specify",
      canonical_relation_type: "specify",
      source_relation_types: ["specify"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:1",
      source_id: "system-model/Requirements/API.md#api-evidence-traceability",
      target_id: "system-model/Capabilities/API.md#api-exploration-capability",
      target_kind: "element",
      relation_type: "specify",
      canonical_relation_type: "specify",
      source_relation_types: ["specify"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:2",
      source_id: "system-model/Contracts/API.md#api-response-contract",
      target_id: "system-model/Requirements/API.md#api-surface-exploration",
      target_kind: "element",
      relation_type: "define",
      canonical_relation_type: "define",
      source_relation_types: ["define"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:3",
      source_id: "system-model/Verifications/API.md#api-smoke-test-verification",
      target_id: "system-model/Verifications/API.md#api-verification-objective",
      target_kind: "element",
      relation_type: "derivedFrom",
      canonical_relation_type: "derivedFrom",
      source_relation_types: ["derivedFrom"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:4",
      source_id: "system-model/Verifications/API.md#api-contract-analysis",
      target_id: "system-model/Verifications/API.md#api-verification-objective",
      target_kind: "element",
      relation_type: "derivedFrom",
      canonical_relation_type: "derivedFrom",
      source_relation_types: ["derivedFrom"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:5",
      source_id: "system-model/Verifications/API.md#api-smoke-test-verification",
      target_id: "system-model/Requirements/API.md#api-surface-exploration",
      target_kind: "element",
      relation_type: "verify",
      canonical_relation_type: "verify",
      source_relation_types: ["verify"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:6",
      source_id: "system-model/Verifications/API.md#api-contract-analysis",
      target_id: "system-model/Requirements/API.md#api-evidence-traceability",
      target_kind: "element",
      relation_type: "verify",
      canonical_relation_type: "verify",
      source_relation_types: ["verify"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:7",
      source_id: "system-model/Verifications/API.md#api-smoke-test-verification",
      target_id: "resource:system-model/Evidence/api-smoke-report.json",
      target_kind: "resource",
      relation_type: "satisfiedBy",
      canonical_relation_type: "satisfiedBy",
      source_relation_types: ["satisfiedBy"],
      authored: true,
      generated_opposite: false,
      resource_id: "resource:system-model/Evidence/api-smoke-report.json",
    },
    {
      id: "rel:api:8",
      source_id: "system-model/Verifications/API.md#api-contract-analysis",
      target_id: "resource:system-model/Evidence/openapi-fragment.yaml",
      target_kind: "resource",
      relation_type: "satisfiedBy",
      canonical_relation_type: "satisfiedBy",
      source_relation_types: ["satisfiedBy"],
      authored: true,
      generated_opposite: false,
      resource_id: "resource:system-model/Evidence/openapi-fragment.yaml",
    },
    {
      id: "rel:api:9",
      source_id: "system-model/Ontologies/API.md#api-shape-contract",
      target_id: "system-model/Ontologies/API.md#api-runtime-ontology",
      target_kind: "element",
      relation_type: "use",
      canonical_relation_type: "use",
      source_relation_types: ["use"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:api:10",
      source_id: "system-model/Ontologies/API.md#api-shape-contract",
      target_id: "system-model/Requirements/API.md#api-surface-exploration",
      target_kind: "element",
      relation_type: "constrain",
      canonical_relation_type: "constrain",
      source_relation_types: ["constrain"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:0",
      source_id: "system-model/Specifications.md#example-verification",
      target_id: "system-model/Specifications.md#example-requirement",
      target_kind: "element",
      relation_type: "verify",
      canonical_relation_type: "verify",
      source_relation_types: ["verify"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
    {
      id: "rel:concept:0",
      source_id: "system-model/Specifications.md#verification-coverage",
      target_id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
      target_kind: "element",
      relation_type: "derivedFrom",
      canonical_relation_type: "derivedFrom",
      source_relation_types: ["derivedFrom"],
      authored: true,
      generated_opposite: false,
      resource_id: null,
    },
  ],
  contract_bindings: [],
  concept_refs: [],
  thesaurus: {
    schemes: [
      {
        id: "urn:reqvire:test:concepts#ExampleThesaurus",
        element_id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        label: "Example Thesaurus",
        definition: "Fixture concept scheme for Explorer Thesaurus development.",
        source_href: "#/content/system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        source_label: "system-model/Thesaurus/Thesaurus.md:60",
        concept_base: "https://example.test/concepts",
        concept_prefix: "concept",
        top_concept_ids: [
          "urn:reqvire:test:concepts#APISurface",
          "urn:reqvire:test:concepts#Traceability",
          "urn:reqvire:test:concepts#VerificationCoverage",
        ],
      },
    ],
    concepts: [
      {
        id: "urn:reqvire:test:concepts#APISurface",
        element_id: "system-model/Thesaurus/Thesaurus.md#api-surface",
        label: "API Surface",
        scheme_id: "urn:reqvire:test:concepts#ExampleThesaurus",
        scheme_element_id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        scheme_label: "Example Thesaurus",
        parent_id: null,
        child_ids: ["urn:reqvire:test:concepts#ServiceEndpoint"],
        definition: "Curated terminology for public API endpoints, operations, and payload boundaries.",
        alt_labels: [],
        scope_note: "",
        example_values: [],
        related_ids: ["urn:reqvire:test:concepts#Traceability"],
        exact_match_ids: [],
        close_match_ids: [],
        used_by: [],
        maps_to: [],
        source_href: "#/content/system-model/Thesaurus/Thesaurus.md#api-surface",
        source_label: "system-model/Thesaurus/Thesaurus.md:64",
      },
      {
        id: "urn:reqvire:test:concepts#ServiceEndpoint",
        element_id: "system-model/Thesaurus/Thesaurus.md#service-endpoint",
        label: "Service Endpoint",
        scheme_id: "urn:reqvire:test:concepts#ExampleThesaurus",
        scheme_element_id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        scheme_label: "Example Thesaurus",
        parent_id: "urn:reqvire:test:concepts#APISurface",
        child_ids: [],
        definition: "A callable service boundary exposed by the system API.",
        alt_labels: ["Endpoint"],
        scope_note: "Use for the addressable API surface. Operation and payload structure stay in the structural ontology.",
        example_values: [],
        related_ids: [],
        exact_match_ids: [],
        close_match_ids: [],
        used_by: [],
        maps_to: [
          {
            id: "urn:reqvire:test:api:ServiceEndpoint",
            label: "ServiceEndpoint",
            type: "class",
          },
        ],
        source_href: "#/content/system-model/Thesaurus/Thesaurus.md#service-endpoint",
        source_label: "system-model/Thesaurus/Thesaurus.md:70",
      },
      {
        id: "urn:reqvire:test:concepts#Traceability",
        element_id: "system-model/Thesaurus/Thesaurus.md#traceability",
        label: "Traceability",
        scheme_id: "urn:reqvire:test:concepts#ExampleThesaurus",
        scheme_element_id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        scheme_label: "Example Thesaurus",
        parent_id: null,
        child_ids: [],
        definition:
          "The ability to follow model intent from capabilities through requirements, contracts, verification, and implementation evidence.",
        alt_labels: [],
        scope_note: "",
        example_values: [],
        related_ids: ["urn:reqvire:test:concepts#APISurface"],
        exact_match_ids: [],
        close_match_ids: [],
        used_by: [],
        maps_to: [],
        source_href: "#/content/system-model/Thesaurus/Thesaurus.md#traceability",
        source_label: "system-model/Thesaurus/Thesaurus.md:80",
      },
      {
        id: "urn:reqvire:test:concepts#VerificationCoverage",
        element_id: "system-model/Specifications.md#verification-coverage",
        label: "Verification Coverage",
        scheme_id: "urn:reqvire:test:concepts#ExampleThesaurus",
        scheme_element_id: "system-model/Thesaurus/Thesaurus.md#fixture-concepts",
        scheme_label: "Example Thesaurus",
        parent_id: null,
        child_ids: [],
        definition: "Closing verification obligations through tests, proofs, analyses, inspections, or demonstrations.",
        alt_labels: [],
        scope_note: "",
        example_values: [],
        related_ids: [],
        exact_match_ids: [],
        close_match_ids: [],
        used_by: [],
        maps_to: [],
        source_href: "#/content/system-model/Specifications.md#verification-coverage",
        source_label: "system-model/Specifications.md:24",
      },
    ],
  },
  submodels: { submodels: [], cross_submodel_couplings: [], summary: {} },
  traces: { files: {} },
  coverage: {
    summary: {
      total_leaf_requirements: 2,
      verified_leaf_requirements: 1,
      unverified_leaf_requirements: 1,
      leaf_requirements_coverage_percentage: 50,
      total_test_verifications: 2,
      satisfied_test_verifications: 1,
      unsatisfied_test_verifications: 1,
      test_verifications_satisfaction_percentage: 50,
      total_verifications: 2,
      orphaned_verifications: 1,
      orphaned_verifications_percentage: 50,
      verification_types: {
        test: 2,
        formal_proof: 0,
        analysis: 0,
        inspection: 0,
        demonstration: 0,
      },
      total_requirements_in_scope: 2,
      covered_requirements: 1,
      uncovered_requirements: 1,
      implementation_coverage_percentage: 50,
      coverage_sources: {
        direct_satisfied: 1,
        contract_satisfied_via_contract_bindings: 0,
        contract_satisfied_via_child: 0,
      },
    },
    verified_leaf_requirements: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-requirement",
            name: "Example Requirement",
            verified_by: ["system-model/Specifications.md#example-verification"],
          },
        ],
      },
    },
    unverified_leaf_requirements: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-unverified-requirement",
            name: "Unverified Fixture Requirement",
            verified_by: [],
          },
        ],
      },
    },
    satisfied_test_verifications: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-verification",
            name: "Example Verification",
            verification_type: "test-verification",
            satisfied_by: ["resource:crates/reqvire-core/src/lib.rs"],
          },
        ],
      },
    },
    unsatisfied_test_verifications: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-unsatisfied-verification",
            name: "Unsatisfied Fixture Verification",
            verification_type: "test-verification",
            satisfied_by: [],
          },
        ],
      },
    },
    orphaned_verifications: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-unsatisfied-verification",
            name: "Unsatisfied Fixture Verification",
            verification_type: "test-verification",
            satisfied_by: [],
          },
        ],
      },
    },
    covered_requirements: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-requirement",
            name: "Example Requirement",
            coverage_source: "direct_satisfied",
            evidence: ["resource:crates/reqvire-core/src/lib.rs"],
          },
        ],
      },
    },
    uncovered_requirements: {
      files: {
        "system-model/Specifications.md": [
          {
            identifier: "system-model/Specifications.md#example-unverified-requirement",
            name: "Unverified Fixture Requirement",
          },
        ],
      },
    },
    capability_coverage: {
      capabilities: [
        {
          identifier: "system-model/Specifications.md#example-capability",
          name: "Example Capability",
          local_leaf_requirements: 2,
          local_verified_leaf_requirements: 1,
          aggregate_leaf_requirements: 2,
          aggregate_verified_leaf_requirements: 1,
          verification_coverage_percentage: 50,
          local_requirements: 2,
          local_covered_requirements: 1,
          aggregate_requirements: 2,
          aggregate_covered_requirements: 1,
          implementation_coverage_percentage: 50,
          mark: "partial",
        },
      ],
    },
  },
  ontology: {
    summary: {
      ontology_blocks: 1,
      shape_blocks: 1,
      total_blocks: 2,
      total_quads: 8,
    },
    declarations: {
      "urn:reqvire:test:api:ServiceEndpoint": [
        {
          iri: "urn:reqvire:test:api:ServiceEndpoint",
          role: "class",
          element_identifier: "system-model/Specifications.md#example-requirement",
        },
      ],
      "urn:reqvire:test:api:identifier": [
        {
          iri: "urn:reqvire:test:api:identifier",
          role: "datatype-property",
          element_identifier: "system-model/Specifications.md#example-requirement",
        },
      ],
    },
    blocks: [
      {
        file_path: "system-model/Specifications.md",
        kind: "ontology",
        line_number: 40,
      },
      {
        file_path: "system-model/Specifications.md",
        kind: "shapes",
        line_number: 58,
      },
    ],
    projection: {
      id: "urn:reqvire:ontology-projection",
      derivation_mode: "direct-authored",
      projections: [
        {
          id: "urn:reqvire:ontology-projection:property-domain-range",
          family: "property-domain-range",
          derivation_mode: "direct-authored",
          construct_ids: [
            "urn:reqvire:ontology-construct:identifier-domain",
            "urn:reqvire:ontology-construct:identifier-range",
          ],
        },
        {
          id: "urn:reqvire:ontology-projection:shape-overlay",
          family: "shape-overlay",
          derivation_mode: "direct-authored",
          construct_ids: ["urn:reqvire:ontology-construct:endpoint-shape"],
        },
      ],
      constructs: [
        {
          id: "urn:reqvire:ontology-construct:identifier-domain",
          family: "property-domain-range",
          kind: "property-domain",
          subject: {
            kind: "iri",
            value: "urn:reqvire:test:api:identifier",
            label: "identifier",
          },
          predicate: {
            kind: "iri",
            value: "http://www.w3.org/2000/01/rdf-schema#domain",
            label: "domain",
          },
          object: {
            kind: "iri",
            value: "urn:reqvire:test:api:ServiceEndpoint",
            label: "ServiceEndpoint",
          },
          provenance: {
            derivation_mode: "direct-authored",
            source: {
              source_block: "system-model/Specifications.md#ontology-1",
              source_element_identifier: "system-model/Specifications.md#example-requirement",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 40,
              block_kind: "ontology",
            },
            evidence: [],
          },
        },
        {
          id: "urn:reqvire:ontology-construct:identifier-range",
          family: "property-domain-range",
          kind: "property-range",
          subject: {
            kind: "iri",
            value: "urn:reqvire:test:api:identifier",
            label: "identifier",
          },
          predicate: {
            kind: "iri",
            value: "http://www.w3.org/2000/01/rdf-schema#range",
            label: "range",
          },
          object: {
            kind: "iri",
            value: "http://www.w3.org/2001/XMLSchema#string",
            label: "string",
          },
          provenance: {
            derivation_mode: "direct-authored",
            source: {
              source_block: "system-model/Specifications.md#ontology-1",
              source_element_identifier: "system-model/Specifications.md#example-requirement",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 41,
              block_kind: "ontology",
            },
            evidence: [],
          },
        },
        {
          id: "urn:reqvire:ontology-construct:endpoint-shape",
          family: "shape-overlay",
          kind: "shape-overlay",
          shape_overlay_kind: "node-shape",
          subject: {
            kind: "iri",
            value: "urn:reqvire:test:api:ServiceEndpointShape",
            label: "ServiceEndpointShape",
          },
          predicate: {
            kind: "iri",
            value: "http://www.w3.org/ns/shacl#targetClass",
            label: "targetClass",
          },
          object: {
            kind: "iri",
            value: "urn:reqvire:test:api:ServiceEndpoint",
            label: "ServiceEndpoint",
          },
          provenance: {
            derivation_mode: "direct-authored",
            source: {
              source_block: "system-model/Specifications.md#shapes-1",
              source_element_identifier: "system-model/Specifications.md#example-requirement",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 58,
              block_kind: "shapes",
            },
            evidence: [],
          },
        },
      ],
      symbols: [],
    },
    graph_data: {
      nodes: [
        {
          id: "urn:reqvire:test:api:ServiceEndpoint",
          label: "ServiceEndpoint",
          type: "class",
          node_type: "class",
          semantic_type: "class",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:ServiceEndpoint",
          comment: "Example ontology class.",
          rdf_types: ["owl:Class"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 40,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
      {
        id: "urn:reqvire:test:api:identifier",
        label: "identifier",
        type: "datatype-property",
          node_type: "datatype-property",
          semantic_type: "datatype-property",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:identifier",
          comment: "Example datatype property.",
          rdf_types: ["owl:DatatypeProperty"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 41,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [{ label: "ServiceEndpoint", iri: "urn:reqvire:test:api:ServiceEndpoint", kind: "class" }],
          range: [{ label: "string", iri: "http://www.w3.org/2001/XMLSchema#string", kind: "datatype" }],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "https://example.test/external#ExternalCode",
          label: "ExternalCode",
          type: "datatype",
          node_type: "datatype",
          semantic_type: "datatype",
          layer: "external-source",
          source_kind: "external-ontology",
          full_uri: "https://example.test/external#ExternalCode",
          ontology_document: "https://example.test/external",
          comment: "Used external ontology subset term materialized from a declared dependency.",
          rdf_types: ["rdfs:Datatype"],
          type_evidence: [],
          sources: [
            {
              source: "reqvire:external-used-subset",
              source_name: "Reqvire used external ontology subset",
              file_path: "",
              line_number: 0,
              kind: "external-used-subset",
              link: "",
            },
          ],
          constraints: [
            { property: "external_materialization", value: "used_subset" },
            { property: "materialized_in_used_subset", value: "true" },
          ],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:api:ApiOperation",
          label: "ApiOperation",
          type: "class",
          node_type: "class",
          semantic_type: "class",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:ApiOperation",
          comment: "Operation exposed by a service endpoint.",
          rdf_types: ["owl:Class"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 42,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:api:RequestPayload",
          label: "RequestPayload",
          type: "class",
          node_type: "class",
          semantic_type: "class",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:RequestPayload",
          comment: "Payload accepted by an API operation.",
          rdf_types: ["owl:Class"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 43,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:api:ErrorResponse",
          label: "ErrorResponse",
          type: "class",
          node_type: "class",
          semantic_type: "class",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:ErrorResponse",
          comment: "Response returned when an API operation fails.",
          rdf_types: ["owl:Class"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 44,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:api:ServiceEndpointShape",
          label: "ServiceEndpointShape",
          type: "node-shape",
          node_type: "node-shape",
          semantic_type: "node-shape",
          layer: "authored",
          source_kind: "shape",
          full_uri: "urn:reqvire:test:api:ServiceEndpointShape",
          comment: "Shape constraining service endpoint terms.",
          rdf_types: ["sh:NodeShape"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#shapes-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 58,
              kind: "shapes",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "http://www.w3.org/2001/XMLSchema#string",
          label: "xsd:string",
          type: "datatype",
          node_type: "datatype",
          semantic_type: "datatype",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "http://www.w3.org/2001/XMLSchema#string",
          comment: "Built-in string datatype used by the fixture property.",
          rdf_types: ["rdfs:Datatype"],
          type_evidence: [],
          sources: [
            {
              source: "built-in",
              source_name: "Built-in Datatype",
              file_path: "system-model/Specifications.md",
              line_number: 41,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:api:hasOperation",
          label: "hasOperation",
          type: "object-property",
          node_type: "object-property",
          semantic_type: "object-property",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:hasOperation",
          comment: "Links an endpoint to an operation.",
          rdf_types: ["owl:ObjectProperty"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 45,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [{ label: "ServiceEndpoint", iri: "urn:reqvire:test:api:ServiceEndpoint", kind: "class" }],
          range: [{ label: "ApiOperation", iri: "urn:reqvire:test:api:ApiOperation", kind: "class" }],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:api:acceptsPayload",
          label: "acceptsPayload",
          type: "object-property",
          node_type: "object-property",
          semantic_type: "object-property",
          layer: "authored",
          source_kind: "ontology",
          full_uri: "urn:reqvire:test:api:acceptsPayload",
          comment: "Links an operation to its request payload.",
          rdf_types: ["owl:ObjectProperty"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Specifications.md#ontology-1",
              source_name: "Example Requirement",
              file_path: "system-model/Specifications.md",
              line_number: 46,
              kind: "ontology",
              link: "#/content/system-model/Specifications.md#example-requirement",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [{ label: "ApiOperation", iri: "urn:reqvire:test:api:ApiOperation", kind: "class" }],
          range: [{ label: "RequestPayload", iri: "urn:reqvire:test:api:RequestPayload", kind: "class" }],
          literal_values: [],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:concepts#ExampleThesaurus",
          label: "Example Thesaurus",
          type: "skos-concept-scheme",
          node_type: "generic",
          semantic_type: "skos-concept-scheme",
          layer: "concepts",
          source_kind: "concepts",
          full_uri: "urn:reqvire:test:concepts#ExampleThesaurus",
          ontology_document: "urn:reqvire:test:concepts",
          scheme_iri: "urn:reqvire:test:concepts#ExampleThesaurus",
          scheme_label: "Example Thesaurus",
          comment: "Fixture concept scheme for API and traceability terminology.",
          rdf_types: ["skos-concept-scheme"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus",
              source_name: "Example Thesaurus",
              file_path: "system-model/Thesaurus/Thesaurus.md",
              line_number: 60,
              kind: "concepts",
              link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [
            { predicate: "skos:prefLabel", value: "Example Thesaurus", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 60, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
            { predicate: "skos:definition", value: "Fixture concept scheme for API and traceability terminology.", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 61, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
          ],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:concepts#ApiSurface",
          label: "API Surface",
          type: "skos-concept",
          node_type: "skos-concept",
          semantic_type: "skos-concept",
          layer: "concepts",
          source_kind: "concepts",
          full_uri: "urn:reqvire:test:concepts#ApiSurface",
          ontology_document: "urn:reqvire:test:concepts",
          scheme_iri: "urn:reqvire:test:concepts#ExampleThesaurus",
          scheme_label: "Example Thesaurus",
          comment: "Public interface concepts used to navigate API-related model elements.",
          rdf_types: ["skos-concept"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus",
              source_name: "Example Thesaurus",
              file_path: "system-model/Thesaurus/Thesaurus.md",
              line_number: 64,
              kind: "concepts",
              link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [
            { predicate: "skos:prefLabel", value: "API Surface", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 64, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
            { predicate: "skos:definition", value: "Curated terminology for public API endpoints, operations, and payload boundaries.", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 65, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
          ],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:concepts#ServiceEndpoint",
          label: "Service Endpoint",
          type: "skos-concept",
          node_type: "skos-concept",
          semantic_type: "skos-concept",
          layer: "concepts",
          source_kind: "concepts",
          full_uri: "urn:reqvire:test:concepts#ServiceEndpoint",
          ontology_document: "urn:reqvire:test:concepts",
          scheme_iri: "urn:reqvire:test:concepts#ExampleThesaurus",
          scheme_label: "Example Thesaurus",
          comment: "Concept for service endpoint terms used by requirements and ontology classes.",
          rdf_types: ["skos-concept"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus",
              source_name: "Example Thesaurus",
              file_path: "system-model/Thesaurus/Thesaurus.md",
              line_number: 70,
              kind: "concepts",
              link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [
            { predicate: "skos:prefLabel", value: "Service Endpoint", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 70, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
            { predicate: "skos:altLabel", value: "Endpoint", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 71, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
            { predicate: "skos:scopeNote", value: "Use for the addressable API surface. Operation and payload structure stay in the structural ontology.", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 72, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
            { predicate: "skos:definition", value: "A callable service boundary exposed by the system API.", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 73, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
          ],
          slot_facets: [],
          constructs: [],
        },
        {
          id: "urn:reqvire:test:concepts#Traceability",
          label: "Traceability",
          type: "skos-concept",
          node_type: "skos-concept",
          semantic_type: "skos-concept",
          layer: "concepts",
          source_kind: "concepts",
          full_uri: "urn:reqvire:test:concepts#Traceability",
          ontology_document: "urn:reqvire:test:concepts",
          scheme_iri: "urn:reqvire:test:concepts#ExampleThesaurus",
          scheme_label: "Example Thesaurus",
          comment: "Concept for navigating engineering lineage and verification context.",
          rdf_types: ["skos-concept"],
          type_evidence: [],
          sources: [
            {
              source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus",
              source_name: "Example Thesaurus",
              file_path: "system-model/Thesaurus/Thesaurus.md",
              line_number: 80,
              kind: "concepts",
              link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus",
            },
          ],
          constraints: [],
          badges: [],
          equivalence_group: "",
          inverse_properties: [],
          property_chains: [],
          domain: [],
          range: [],
          literal_values: [
            { predicate: "skos:prefLabel", value: "Traceability", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 80, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
            { predicate: "skos:definition", value: "The ability to follow model intent from capabilities through requirements, contracts, verification, and implementation evidence.", source: { source: "system-model/Thesaurus/Thesaurus.md#example-thesaurus", source_name: "Example Thesaurus", file_path: "system-model/Thesaurus/Thesaurus.md", line_number: 81, kind: "concepts", link: "#/content/system-model/Thesaurus/Thesaurus.md#example-thesaurus" } },
          ],
          slot_facets: [],
          constructs: [],
        },
      ],
      edges: [
        {
          source: "urn:reqvire:test:api:identifier",
          target: "urn:reqvire:test:api:ServiceEndpoint",
          label: "domain",
          layer: "authored",
          source_kind: "ontology",
        },
        {
          source: "urn:reqvire:test:api:ApiOperation",
          target: "urn:reqvire:test:api:ServiceEndpoint",
          label: "subclass",
          layer: "authored",
          source_kind: "ontology",
        },
        {
          source: "urn:reqvire:test:api:ErrorResponse",
          target: "urn:reqvire:test:api:ApiOperation",
          label: "subclass",
          layer: "authored",
          source_kind: "ontology",
        },
        {
          source: "urn:reqvire:test:api:ServiceEndpointShape",
          target: "urn:reqvire:test:api:ServiceEndpoint",
          label: "shape overlay",
          layer: "authored",
          source_kind: "shape",
        },
        {
          source: "urn:reqvire:test:concepts#ApiSurface",
          target: "urn:reqvire:test:concepts#ExampleThesaurus",
          label: "inScheme",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#ServiceEndpoint",
          target: "urn:reqvire:test:concepts#ExampleThesaurus",
          label: "inScheme",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#Traceability",
          target: "urn:reqvire:test:concepts#ExampleThesaurus",
          label: "inScheme",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#ExampleThesaurus",
          target: "urn:reqvire:test:concepts#ApiSurface",
          label: "hasTopConcept",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#ExampleThesaurus",
          target: "urn:reqvire:test:concepts#Traceability",
          label: "hasTopConcept",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#ServiceEndpoint",
          target: "urn:reqvire:test:concepts#ApiSurface",
          label: "broader",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#Traceability",
          target: "urn:reqvire:test:concepts#ApiSurface",
          label: "related",
          layer: "concepts",
          source_kind: "concepts",
        },
        {
          source: "urn:reqvire:test:concepts#ServiceEndpoint",
          target: "urn:reqvire:test:api:ServiceEndpoint",
          label: "mapsToConcept",
          layer: "concepts",
          source_kind: "concepts",
        },
      ],
    },
    ttl_href: "ontologies.ttl",
  },
  knowledge_graph: {
    nodes: [
      {
        id: "system-model/Specifications.md#example-capability",
        identifier: "system-model/Specifications.md#example-capability",
        label: "Example Capability",
        type: "capability",
        node_type: "capability",
        element_type: "capability",
        file_path: "system-model/Specifications.md",
        line_number: 1,
        link: "#/content/system-model/Specifications.md#example-capability",
        description: "Capability root for the fixture project graph.",
        metadata: [{ name: "type", value: "capability", link: "", kind: "metadata" }],
        governance: [{ name: "status", value: "draft", link: "", kind: "governance" }],
        outgoing: [],
        incoming: [
          { name: "specifiedBy", value: "Example Requirement", link: "", kind: "authored" },
          { name: "specifiedBy", value: "Unverified Fixture Requirement", link: "", kind: "authored" },
        ],
        contract_bindings: [],
        concept_references: [],
      },
      {
        id: "system-model/Specifications.md#example-requirement",
        identifier: "system-model/Specifications.md#example-requirement",
        label: "Example Requirement",
        type: "requirement",
        node_type: "requirement",
        element_type: "requirement",
        file_path: "system-model/Specifications.md",
        line_number: 3,
        link: "#/content/system-model/Specifications.md#example-requirement",
        description: "The system shall demonstrate the Explorer shell with fixture data.",
        metadata: [{ name: "type", value: "requirement", link: "", kind: "metadata" }],
        governance: [{ name: "status", value: "draft", link: "", kind: "governance" }],
        outgoing: [
          { name: "specify", value: "Example Capability", link: "", kind: "authored" },
          { name: "definedBy", value: "Fixture Interface Contract", link: "", kind: "authored" },
        ],
        incoming: [
          { name: "verify", value: "Example Verification", link: "", kind: "authored" },
          { name: "references", value: "Service Endpoint", link: "", kind: "concept-reference" },
        ],
        contract_bindings: [],
        concept_references: [
          { name: "Service Endpoint", value: "urn:reqvire:test:concepts#ServiceEndpoint", link: "", kind: "concept-reference" },
        ],
      },
      {
        id: "system-model/Specifications.md#example-unverified-requirement",
        identifier: "system-model/Specifications.md#example-unverified-requirement",
        label: "Unverified Fixture Requirement",
        type: "requirement",
        node_type: "requirement",
        element_type: "requirement",
        file_path: "system-model/Specifications.md",
        line_number: 12,
        link: "#/content/system-model/Specifications.md#example-unverified-requirement",
        description: "Requirement branch with no verifying evidence.",
        metadata: [{ name: "type", value: "requirement", link: "", kind: "metadata" }],
        governance: [{ name: "status", value: "draft", link: "", kind: "governance" }],
        outgoing: [{ name: "specify", value: "Example Capability", link: "", kind: "authored" }],
        incoming: [],
        contract_bindings: [],
        concept_references: [],
      },
      {
        id: "system-model/Specifications.md#fixture-interface-contract",
        identifier: "system-model/Specifications.md#fixture-interface-contract",
        label: "Fixture Interface Contract",
        type: "specification",
        node_type: "specification",
        element_type: "specification",
        file_path: "system-model/Specifications.md",
        line_number: 16,
        link: "#/content/system-model/Specifications.md#fixture-interface-contract",
        description: "Requirement-owned fixture contract used as a neighboring graph branch.",
        metadata: [{ name: "type", value: "specification", link: "", kind: "metadata" }],
        governance: [],
        outgoing: [{ name: "define", value: "Example Requirement", link: "", kind: "authored" }],
        incoming: [],
        contract_bindings: [],
        concept_references: [],
      },
      {
        id: "system-model/Specifications.md#fixture-verification-objective",
        identifier: "system-model/Specifications.md#fixture-verification-objective",
        label: "Fixture Verification Objective",
        type: "verification-objective",
        node_type: "verification-objective",
        element_type: "verification-objective",
        file_path: "system-model/Specifications.md",
        line_number: 18,
        link: "#/content/system-model/Specifications.md#fixture-verification-objective",
        description: "Verification objective that groups fixture verification work.",
        metadata: [{ name: "type", value: "verification-objective", link: "", kind: "metadata" }],
        governance: [],
        outgoing: [],
        incoming: [
          { name: "derive", value: "Example Verification", link: "", kind: "authored" },
          { name: "derive", value: "Unsatisfied Fixture Verification", link: "", kind: "authored" },
        ],
        contract_bindings: [],
        concept_references: [],
      },
      {
        id: "system-model/Specifications.md#example-verification",
        identifier: "system-model/Specifications.md#example-verification",
        label: "Example Verification",
        type: "verification",
        node_type: "verification",
        element_type: "test-verification",
        file_path: "system-model/Specifications.md",
        line_number: 20,
        link: "#/content/system-model/Specifications.md#example-verification",
        description: "Verifies the Example Requirement via a test.",
        metadata: [{ name: "type", value: "test-verification", link: "", kind: "metadata" }],
        governance: [],
        outgoing: [
          { name: "verify", value: "Example Requirement", link: "", kind: "authored" },
          { name: "derivedFrom", value: "Fixture Verification Objective", link: "", kind: "authored" },
          { name: "satisfiedBy", value: "lib.rs", link: "", kind: "authored" },
        ],
        incoming: [],
        contract_bindings: [],
        concept_references: [],
      },
      {
        id: "system-model/Specifications.md#example-unsatisfied-verification",
        identifier: "system-model/Specifications.md#example-unsatisfied-verification",
        label: "Unsatisfied Fixture Verification",
        type: "verification",
        node_type: "verification",
        element_type: "test-verification",
        file_path: "system-model/Specifications.md",
        line_number: 28,
        link: "#/content/system-model/Specifications.md#example-unsatisfied-verification",
        description: "Concrete verification branch with no evidence.",
        metadata: [{ name: "type", value: "test-verification", link: "", kind: "metadata" }],
        governance: [],
        outgoing: [{ name: "derivedFrom", value: "Fixture Verification Objective", link: "", kind: "authored" }],
        incoming: [],
        contract_bindings: [],
        concept_references: [],
      },
      {
        id: "resource:crates/reqvire-core/src/lib.rs",
        identifier: "resource:crates/reqvire-core/src/lib.rs",
        label: "lib.rs",
        type: "resource",
        node_type: "resource",
        element_type: "resource",
        file_path: "crates/reqvire-core/src/lib.rs",
        line_number: 1,
        link: "#/content/crates/reqvire-core/src/lib.rs",
        description: "Fixture implementation evidence resource.",
        metadata: [{ name: "kind", value: "local-file", link: "", kind: "metadata" }],
        governance: [],
        outgoing: [],
        incoming: [{ name: "satisfiedBy", value: "Example Verification", link: "", kind: "authored" }],
        contract_bindings: [],
        concept_references: [],
      },
    ],
    edges: [
      {
        source: "system-model/Specifications.md#example-requirement",
        target: "system-model/Specifications.md#example-capability",
        label: "specify",
        kind: "authored",
        authored: true,
      },
      {
        source: "system-model/Specifications.md#example-unverified-requirement",
        target: "system-model/Specifications.md#example-capability",
        label: "specify",
        kind: "authored",
        authored: true,
      },
      {
        source: "system-model/Specifications.md#fixture-interface-contract",
        target: "system-model/Specifications.md#example-requirement",
        label: "define",
        kind: "authored",
        authored: true,
      },
      {
        source: "system-model/Specifications.md#example-verification",
        target: "system-model/Specifications.md#fixture-verification-objective",
        label: "derivedFrom",
        kind: "authored",
        authored: true,
      },
      {
        source: "system-model/Specifications.md#example-verification",
        target: "system-model/Specifications.md#example-requirement",
        label: "verify",
        kind: "authored",
        authored: true,
      },
      {
        source: "system-model/Specifications.md#example-unsatisfied-verification",
        target: "system-model/Specifications.md#fixture-verification-objective",
        label: "derivedFrom",
        kind: "authored",
        authored: true,
      },
      {
        source: "system-model/Specifications.md#example-verification",
        target: "resource:crates/reqvire-core/src/lib.rs",
        label: "satisfiedBy",
        kind: "authored",
        authored: true,
      },
    ],
    submodels: [
      {
        root_id: "system-model/Specifications.md#example-requirement",
        root_name: "Example Requirement",
        root_type: "requirement",
        requirement_count: 1,
      },
    ],
    summary: {
      elements: 16,
      relations: 19,
      contract_bindings: 0,
      concept_references: 1,
      resources: 3,
      submodels: 1,
    },
  },
  search: [
    {
      id: "system-model/Specifications.md#example-requirement",
      kind: "element",
      title: "Example Requirement",
      route: "#/elements/system-model/Specifications.md#example-requirement",
      text: "Example Requirement requirement demonstrate Explorer shell",
    },
  ],
  summaries: {
    elements: 16,
    files: 9,
    folders: 7,
    resources: 3,
    relations: 13,
    contract_bindings: 0,
    concept_refs: 0,
    ontology_blocks: 0,
    shape_blocks: 0,
  },
  routes: {
    canonical: [
      { id: "model", pattern: "#/model", title: "Model" },
      { id: "traces", pattern: "#/traces", title: "Traces" },
      { id: "ontologies", pattern: "#/ontologies", title: "Ontologies" },
    ],
  },
};
