use maud::{html, Markup, DOCTYPE, PreEscaped};

/// Base layout for standard pages with Tailwind responsive design
pub fn base(title: &str, content: Markup, nav_prefix: &str) -> Markup {
    html! {
        (DOCTYPE)
        html lang="en" {
            head {
                meta charset="UTF-8";
                meta name="viewport" content="width=device-width, initial-scale=1.0";
                title { (title) }
                link rel="icon" type="image/x-icon" href={(nav_prefix)"assets/favicon.ico"};
                link rel="apple-touch-icon" href={(nav_prefix)"assets/apple-touch-icon.png"};

                // Tailwind CSS CDN
                script src="https://cdn.tailwindcss.com" {}

                // Custom CSS for Mermaid, content styling, and color scheme
                (super::styles::custom())
            }
            body class="bg-gray-50" {
                // Navigation bar with responsive mobile menu
                nav class="reqvire-nav fixed top-0 left-0 right-0 h-[50px] shadow-md z-[1000] flex items-center px-5" style="background-color: #3F51B5;" {
                    // Logo
                    a href={(nav_prefix)"index.html"} class="nav-logo flex items-center pr-4" {
                        img src={(nav_prefix)"assets/logo.png"} alt="Reqvire" height="24";
                    }

                    // Desktop navigation (hidden on mobile)
                    div class="hidden md:flex md:items-center md:gap-1" {
                        a href={(nav_prefix)"index.html"} class="nav-link" { "Containment" }
                        a href={(nav_prefix)"model.html"} class="nav-link" { "Model" }
                        a href={(nav_prefix)"traces.html"} class="nav-link" { "Traces" }
                        a href={(nav_prefix)"traceflow.html"} class="nav-link" { "TraceFlow" }
                        a href={(nav_prefix)"coverage.html"} class="nav-link" { "Coverage" }
                        a href={(nav_prefix)"resources.html"} class="nav-link" { "Resources" }
                    }

                    // Mobile menu button (visible on mobile only)
                    button id="mobile-menu-btn" class="md:hidden ml-auto text-white p-2 rounded"
                            style="transition: background-color 0.2s;"
                            onmouseover="this.style.backgroundColor='#7986CB'"
                            onmouseout="this.style.backgroundColor='transparent'"
                            aria-label="Toggle menu" {
                        // Hamburger icon
                        svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" {
                            path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M4 6h16M4 12h16M4 18h16" {}
                        }
                    }
                }

                // Mobile menu (hidden by default, shown when hamburger clicked)
                div id="mobile-menu" class="hidden md:hidden fixed top-[50px] left-0 right-0 shadow-lg z-[999]" style="background-color: #3F51B5;" {
                    div class="flex flex-col" {
                        a href={(nav_prefix)"index.html"} class="mobile-nav-link" { "Containment" }
                        a href={(nav_prefix)"model.html"} class="mobile-nav-link" { "Model" }
                        a href={(nav_prefix)"traces.html"} class="mobile-nav-link" { "Traces" }
                        a href={(nav_prefix)"traceflow.html"} class="mobile-nav-link" { "TraceFlow" }
                        a href={(nav_prefix)"coverage.html"} class="mobile-nav-link" { "Coverage" }
                        a href={(nav_prefix)"resources.html"} class="mobile-nav-link" { "Resources" }
                    }
                }

                // Spacer for fixed nav
                div class="h-[50px]" {}

                // Main content with responsive fluid width
                div class="w-full max-w-[95%] mx-auto p-5" {
                    div class="bg-white p-8 rounded shadow-sm border border-gray-200" {
                        (content)
                        footer class="mt-8 pt-5 border-t border-gray-200 text-center text-gray-600 text-sm" {
                            "Generated by "
                            a href="https://reqvire.org" class="text-indigo-700 no-underline hover:underline" { "Reqvire" }
                        }
                    }
                }

                // Mobile menu toggle script
                script {
                    (PreEscaped(r#"
                        document.getElementById('mobile-menu-btn').addEventListener('click', function() {
                            var menu = document.getElementById('mobile-menu');
                            menu.classList.toggle('hidden');
                        });
                    "#))
                }
            }
        }
    }
}

/// Diagram layout for full-height visualizations with Tailwind responsive design
pub fn diagram_layout(title: &str, diagram: Markup, nav_prefix: &str) -> Markup {
    html! {
        (DOCTYPE)
        html lang="en" {
            head {
                meta charset="UTF-8";
                meta name="viewport" content="width=device-width, initial-scale=1.0";
                title { (title) }
                link rel="icon" type="image/x-icon" href={(nav_prefix)"assets/favicon.ico"};
                link rel="apple-touch-icon" href={(nav_prefix)"assets/apple-touch-icon.png"};

                // Tailwind CSS CDN
                script src="https://cdn.tailwindcss.com" {}

                // Custom CSS for Mermaid, content styling, and color scheme
                (super::styles::custom())

                // Include Mermaid scripts for diagrams
                (super::visualizations::mermaid::scripts())
            }
            body class="bg-gray-50" {
                // Navigation bar with responsive mobile menu
                nav class="reqvire-nav fixed top-0 left-0 right-0 h-[50px] shadow-md z-[1000] flex items-center px-5" style="background-color: #3F51B5;" {
                    // Logo
                    a href={(nav_prefix)"index.html"} class="nav-logo flex items-center pr-4" {
                        img src={(nav_prefix)"assets/logo.png"} alt="Reqvire" height="24";
                    }

                    // Desktop navigation (hidden on mobile)
                    div class="hidden md:flex md:items-center md:gap-1" {
                        a href={(nav_prefix)"index.html"} class="nav-link" { "Containment" }
                        a href={(nav_prefix)"model.html"} class="nav-link" { "Model" }
                        a href={(nav_prefix)"traces.html"} class="nav-link" { "Traces" }
                        a href={(nav_prefix)"traceflow.html"} class="nav-link" { "TraceFlow" }
                        a href={(nav_prefix)"coverage.html"} class="nav-link" { "Coverage" }
                        a href={(nav_prefix)"resources.html"} class="nav-link" { "Resources" }
                    }

                    // Mobile menu button (visible on mobile only)
                    button id="mobile-menu-btn" class="md:hidden ml-auto text-white p-2 rounded"
                            style="transition: background-color 0.2s;"
                            onmouseover="this.style.backgroundColor='#7986CB'"
                            onmouseout="this.style.backgroundColor='transparent'"
                            aria-label="Toggle menu" {
                        // Hamburger icon
                        svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" {
                            path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M4 6h16M4 12h16M4 18h16" {}
                        }
                    }
                }

                // Mobile menu (hidden by default, shown when hamburger clicked)
                div id="mobile-menu" class="hidden md:hidden fixed top-[50px] left-0 right-0 shadow-lg z-[999]" style="background-color: #3F51B5;" {
                    div class="flex flex-col" {
                        a href={(nav_prefix)"index.html"} class="mobile-nav-link" { "Containment" }
                        a href={(nav_prefix)"model.html"} class="mobile-nav-link" { "Model" }
                        a href={(nav_prefix)"traces.html"} class="mobile-nav-link" { "Traces" }
                        a href={(nav_prefix)"traceflow.html"} class="mobile-nav-link" { "TraceFlow" }
                        a href={(nav_prefix)"coverage.html"} class="mobile-nav-link" { "Coverage" }
                        a href={(nav_prefix)"resources.html"} class="mobile-nav-link" { "Resources" }
                    }
                }

                // Spacer for fixed nav
                div class="h-[50px]" {}

                // Main content with responsive fluid width
                div class="w-full max-w-[95%] mx-auto p-5" {
                    div class="bg-white p-8 rounded shadow-sm border border-gray-200" {
                        (diagram)
                        footer class="mt-8 pt-5 border-t border-gray-200 text-center text-gray-600 text-sm" {
                            "Generated by "
                            a href="https://reqvire.org" class="text-indigo-700 no-underline hover:underline" { "Reqvire" }
                        }
                    }
                }

                // Mobile menu toggle script
                script {
                    (PreEscaped(r#"
                        document.getElementById('mobile-menu-btn').addEventListener('click', function() {
                            var menu = document.getElementById('mobile-menu');
                            menu.classList.toggle('hidden');
                        });
                    "#))
                }
            }
        }
    }
}
