#!/bin/bash

# Test: Diagram Generation Functionality
# --------------------------------------
# Acceptance Criteria:
# - System should generate diagrams embedded in markdown files
# - System should add/update mermaid diagrams under section headers
# - System should preserve existing custom mermaid diagrams
# - All auto-generated diagrams must include REQVIRE-AUTOGENERATED-DIAGRAM marker
#
# Test Criteria:
# - Command exits with success (0) return code
# - Modified files contain the expected mermaid diagrams
# - Custom diagrams are preserved
# - Generated diagrams have proper content and relationships
# - All auto-generated diagrams contain the REQVIRE-AUTOGENERATED-DIAGRAM marker


# Create a reqvire.yaml configuration
cat > "$TEST_DIR/reqvire.yaml" << EOF
paths:
  output_folder: "output"
  excluded_filename_patterns: []
style:
  theme: "default"
  max_width: 1200
  diagram_direction: "LR"
EOF

# Make backup copies of original files for comparison
mkdir -p "$TEST_DIR/backup"
cp -r "$TEST_DIR/specifications" "$TEST_DIR/backup/"

# Run reqvire to generate diagrams (validation happens automatically)
OUTPUT=$(cd "$TEST_DIR" && "$REQVIRE_BIN" --config "$TEST_DIR/reqvire.yaml" generate-diagrams 2>&1)
EXIT_CODE=$?

# Save output to log
printf "%s\n" "$OUTPUT" > "${TEST_DIR}/test_results.log"

# Check for basic success
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ FAILED: Diagram generation command returned error: $EXIT_CODE"
  cat "${TEST_DIR}/test_results.log"
  exit 1
fi

# List of files to check
FILES_TO_CHECK=(
  "Requirements.md"
  "Requirements-with-custom-mermaid.md"
  "SystemRequirements.md" 
  "UserRequirements.md"
  "VerificationTests.md"
)

# Check if files were modified and contain mermaid diagrams
FAILED_CHECKS=0
for file in "${FILES_TO_CHECK[@]}"; do
  file_path="$TEST_DIR/specifications/$file"
  backup_path="$TEST_DIR/backup/specifications/$file"
  
  # Check that files were modified
  if cmp -s "$file_path" "$backup_path"; then
    echo "❌ NOT MODIFIED: Expected file to be modified with diagrams: $file"
    FAILED_CHECKS=$((FAILED_CHECKS + 1))
    continue
  fi
  
  # Check for mermaid content
  if ! grep -q '```mermaid' "$file_path"; then
    echo "❌ NO DIAGRAM: Expected file to contain mermaid diagram: $file"
    FAILED_CHECKS=$((FAILED_CHECKS + 1))
    continue
  fi

  # Check that auto-generated diagrams contain the marker
  DIAGRAM_COUNT=$(grep -c '```mermaid' "$file_path")
  MARKER_COUNT=$(grep -c 'REQVIRE-AUTOGENERATED-DIAGRAM' "$file_path")

  # For files that should have auto-generated diagrams, check marker presence
  case "$file" in
    "Requirements-with-custom-mermaid.md")
      # This file has both custom and auto-generated diagrams
      # Should have at least 1 marker (for auto-generated) but not for all diagrams (custom preserved)
      if [ $MARKER_COUNT -eq 0 ]; then
        echo "❌ MISSING MARKER: Expected auto-generated diagrams to contain REQVIRE-AUTOGENERATED-DIAGRAM marker in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      # Verify custom diagram doesn't have marker
      CUSTOM_DIAGRAM_SECTION=$(sed -n '/flowchart TD/,/```$/p' "$file_path")
      if echo "$CUSTOM_DIAGRAM_SECTION" | grep -q 'REQVIRE-AUTOGENERATED-DIAGRAM'; then
        echo "❌ MARKER IN CUSTOM: Custom diagram should not contain REQVIRE-AUTOGENERATED-DIAGRAM marker in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      ;;
    *)
      # For files with only auto-generated diagrams, all should have markers
      if [ $MARKER_COUNT -eq 0 ]; then
        echo "❌ MISSING MARKER: Expected auto-generated diagrams to contain REQVIRE-AUTOGENERATED-DIAGRAM marker in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      ;;
  esac
  
  
  # For files with diagrams, check if they contain expected elements
  case "$file" in
    "Requirements.md")
      if ! grep -q 'Element 1' "$file_path"; then
        echo "❌ MISSING CONTENT: Expected diagram to contain 'Element 1' in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      ;;
    "Requirements-with-custom-mermaid.md")
      # For the custom mermaid file, ensure the custom flowchart diagram is preserved
      if ! grep -q 'flowchart TD' "$file_path"; then
        echo "❌ LOST CONTENT: Custom flowchart diagram not preserved in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      if ! grep -q 'A\[Start\] --> B{Is it?}' "$file_path"; then
        echo "❌ LOST CONTENT: Custom flowchart content not preserved in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      ;;
    *)
      # Generic checks for other files
      # Look for any node/class definition
      if ! grep -q 'class [a-zA-Z0-9]' "$file_path"; then
        echo "❌ MISSING CONTENT: Expected diagram to contain class definitions in $file"
        FAILED_CHECKS=$((FAILED_CHECKS + 1))
      fi
      ;;
  esac
done

if [ $FAILED_CHECKS -gt 0 ]; then
  echo "❌ FAILED: $FAILED_CHECKS diagram checks failed"
  exit 1
fi


# Perform a specific check for relationships in diagrams and if rendered with right arrow
if ! grep -q -- "-.->|verifiedBy|" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Missing relationships in Requirements.md diagram"
  exit 1
fi

# Perform a specific check for relationships in diagrams and if rendered with right arrow
if ! grep -q -- "-.->|trace|" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Missing relationships in Requirements.md diagram"
  exit 1
fi

# Perform a specific check for relationships in diagrams and if rendered with right arrow
if ! grep -q -- "-->|refinedBy|" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Missing relationships in Requirements.md diagram"
  exit 1
fi

# Perform a specific check for relationships in diagrams and if rendered with right arrow
if ! grep -q -- "--o|contains" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Missing relationships in Requirements.md diagram"
  exit 1
fi

# Perform a specific check for relationships in diagrams and if rendered with right arrow
if ! grep -q -- "-.->|deriveReqT" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Missing relationships in Requirements.md diagram"
  exit 1
fi

# Perform a specific check for relationships in diagrams and if rendered with right arrow
if ! grep -q -- "-->|satisfiedBy|" "$TEST_DIR/specifications/Requirements.md"; then
  echo "❌ FAILED: Missing relationships in Requirements.md diagram"
  exit 1
fi
  

exit 0
