#!/bin/bash
set -uo pipefail

TEST_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create log file immediately to ensure it exists for runner
echo "Starting test..." > "${TEST_DIR}/test_results.log"

# Test: Diagram Generation Functionality
# --------------------------------------
# Acceptance Criteria:
# - System should generate diagrams embedded in markdown files
# - System should add/update mermaid diagrams under section headers
# - System should preserve existing custom mermaid diagrams
# - All auto-generated diagrams must include REQVIRE-AUTOGENERATED-DIAGRAM marker
#
# Test Criteria:
# - Command exits with success (0) return code
# - Modified files contain the expected mermaid diagrams
# - Custom diagrams are preserved
# - Generated diagrams have proper content and relationships
# - All auto-generated diagrams contain the REQVIRE-AUTOGENERATED-DIAGRAM marker

# Helper function to compare files and show diff on failure
assert_file_matches() {
  local expected="$1"
  local actual="$2"
  local description="$3"

  if ! diff -u "$expected" "$actual"; then
    echo "❌ FAILED: $description"
    echo ""
    echo "If changes are intentional, update the expected file:"
    echo "  cp $actual $expected"
    exit 1
  fi
}

# Run reqvire to generate diagrams (validation happens automatically)
echo "Running: reqvire generate-diagrams" >> "${TEST_DIR}/test_results.log"
set +e
OUTPUT=$(cd "$TEST_DIR" && "$REQVIRE_BIN" generate-diagrams 2>&1)
EXIT_CODE=$?
set -e

echo "Exit code: $EXIT_CODE" >> "${TEST_DIR}/test_results.log"
printf "%s\n" "$OUTPUT" >> "${TEST_DIR}/test_results.log"

# Check for basic success
if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ FAILED: Diagram generation command returned error: $EXIT_CODE"
  echo "$OUTPUT"
  exit 1
fi

# Compare all generated files against expected output
assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/Requirements.md" \
  "$TEST_DIR/specifications/Requirements.md" \
  "Requirements.md after diagram generation does not match expected"

assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/Requirements-with-custom-mermaid.md" \
  "$TEST_DIR/specifications/Requirements-with-custom-mermaid.md" \
  "Requirements-with-custom-mermaid.md after diagram generation does not match expected"

assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/SystemRequirements.md" \
  "$TEST_DIR/specifications/SystemRequirements.md" \
  "SystemRequirements.md after diagram generation does not match expected"

assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/UserRequirements.md" \
  "$TEST_DIR/specifications/UserRequirements.md" \
  "UserRequirements.md after diagram generation does not match expected"

assert_file_matches \
  "${TEST_SCRIPT_DIR}/expected/VerificationTests.md" \
  "$TEST_DIR/specifications/VerificationTests.md" \
  "VerificationTests.md after diagram generation does not match expected"

exit 0
