pub mod builtin_external_sources;
pub mod change_impact;
pub(crate) mod concept;
pub mod config;
pub mod containment;
pub mod crud;
pub mod diff;
pub mod element;
pub mod error;
pub mod explorer_runtime;
pub mod filesystem;
pub mod filters;
pub mod format;
pub mod git_commands;
pub mod graph_registry;
pub mod html;
pub mod lint;
pub mod mcp_prompts;
pub mod migrations;
pub mod model;
pub mod model_cache;
pub mod ontology_graph;
pub mod operations;
pub mod parser;
pub(crate) mod rdf_store;
pub mod relation;
pub mod report;
pub mod runtime_ontology;
pub mod search;
pub mod semantic_contract;
pub mod semantic_store;
pub mod subsection;
#[cfg(test)]
pub(crate) mod test_support;
pub mod tool_interface;
pub mod trace_tree_builder;
pub mod utils;
pub mod verification_trace;
pub mod workspace;

// Re-export commonly used modules
pub use crate::element::Element;
pub use crate::error::{ErrorContext, ReqvireError, ValidationDiagnostic};
pub use crate::graph_registry::GraphRegistry;
pub use crate::model::{ModelBuildOptions, ModelManager};
pub use crate::relation::Relation;
pub use o_kernel::{constructs, diagnostics, ontology, owl_reserved, rdf, shacl, subset, vocab};
