//! Build script: embeds the built Explorer SPA (Vite) `dist/`.
//!
//! By default, `cargo build` consumes an existing `explorer/dist`. Set
//! `REQVIRE_BUILD_EXPLORER=1` to run `npm run build` in the repository
//! `explorer` directory first.
//! The script then recursively copies `explorer/dist` into
//! `OUT_DIR/explorer_bundle` and generates a manifest of `(relative_path,
//! bytes)` that `src/explorer_runtime.rs` consumes via `include!`.
//!
//! Vite/Explorer is the single source of truth for ALL bundle assets
//! (index.html, JS/CSS, favicons, logos, fonts). Rust embeds them verbatim and
//! owns none of them.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("environment variable not set"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("environment variable not set"));
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("reqvire-core crate should live under crates/");
    let explorer_dir = repo_root.join("explorer");
    let dist = explorer_dir.join("dist");

    let rebuild = env::var_os("REQVIRE_BUILD_EXPLORER").is_some();
    // Watch source inputs, not generated kit/showcase output or our own build output.
    // Prebuilt mode also watches dist because another build owns that input.
    for p in [
        "src",
        "public",
        "scripts",
        "index.html",
        "package.json",
        "package-lock.json",
        "vite.config.ts",
        "tsconfig.json",
        "vitest.config.ts",
        ".stylelintrc.json",
        ".oxlintignore",
        "design-system/assets",
        "design-system/components",
        "design-system/hooks",
        "design-system/showcase",
        "design-system/product-patterns",
        "design-system/tokens",
        "design-system/index.ts",
        "design-system/palette.ts",
        "design-system/styles.css",
        "design-system/vite.assetMerge.ts",
        "design-system/vite.bundle.config.ts",
        "design-system/vite.showcase.config.ts",
    ] {
        let input = explorer_dir.join(p);
        // Cargo treats a nonexistent watched path as perpetually dirty.
        if input.exists() {
            println!("cargo:rerun-if-changed={}", input.display());
        }
    }
    if !rebuild {
        println!("cargo:rerun-if-changed={}", dist.display());
    }
    println!("cargo:rerun-if-env-changed=REQVIRE_BUILD_EXPLORER");

    // Build the Explorer SPA only when explicitly requested.
    if rebuild {
        let status = Command::new("npm")
            .arg("run")
            .arg("build")
            .current_dir(&explorer_dir)
            .status()
            .unwrap_or_else(|error| panic!(
                "could not run `npm run build` in {} ({error}); install Node/npm and run `cd explorer && npm ci` first",
                explorer_dir.display()
            ));
        assert!(status.success(), "`npm run build` failed (status {status}) in {}; refusing to embed stale Explorer assets", explorer_dir.display());
    }

    if !dist.join("index.html").is_file() {
        panic!(
            "explorer/dist bundle not found at {}. Run `cd explorer && npm ci && npm run build` first.",
            dist.display()
        );
    }

    // Synchronize without rewriting identical assets or retaining removed ones.
    let bundle_out = out_dir.join("explorer_bundle");

    let mut files: Vec<String> = Vec::new();
    copy_tree(&dist, &dist, &bundle_out, &mut files);
    files.sort();

    // Generate the manifest consumed by src/explorer_runtime.rs via include!().
    let mut manifest = String::from("// @generated by build.rs - embedded Explorer dist bundle\n");
    manifest.push_str("pub static EMBEDDED_BUNDLE: &[(&str, &[u8])] = &[\n");
    for rel in &files {
        let abs = bundle_out.join(rel);
        manifest.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            rel,
            abs.display().to_string()
        ));
    }
    manifest.push_str("];\n");
    write_if_changed(
        &out_dir.join("explorer_bundle_manifest.rs"),
        manifest.as_bytes(),
    );
}

/// Recursively copies files under `src` into `dst_root/<path relative to root>`,
/// recording POSIX-style relative paths into `files`.
fn copy_tree(root: &Path, src: &Path, dst_root: &Path, files: &mut Vec<String>) {
    let dest_dir = dst_root.join(src.strip_prefix(root).expect("relative source directory"));
    if dest_dir.is_file() {
        fs::remove_file(&dest_dir).expect("remove replaced asset file");
    }
    fs::create_dir_all(&dest_dir).expect("create bundle directory");
    for entry in fs::read_dir(&dest_dir).expect("read bundle directory") {
        let path = entry.expect("bundle entry").path();
        let source = src.join(path.file_name().expect("bundle entry name"));
        if !source.exists() || source.is_dir() != path.is_dir() {
            if path.is_dir() {
                fs::remove_dir_all(&path).expect("remove obsolete bundle directory");
            } else {
                fs::remove_file(&path).expect("remove obsolete bundle asset");
            }
        }
    }
    for entry in fs::read_dir(src).unwrap_or_else(|e| panic!("read dir {}: {e}", src.display())) {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            copy_tree(root, &path, dst_root, files);
        } else if path.is_file() {
            let rel = path.strip_prefix(root).expect("relative asset path");
            let content =
                fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            write_if_changed(&dst_root.join(rel), &content);
            files.push(rel.to_string_lossy().replace('\\', "/"));
        }
    }
}

fn write_if_changed(path: &Path, content: &[u8]) {
    match fs::read(path) {
        Ok(existing) if existing == content => return,
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => panic!("read {}: {error}", path.display()),
    }
    fs::write(path, content).unwrap_or_else(|error| panic!("write {}: {error}", path.display()));
}
